### ISSUE TITLE
nmonmerge and NmonVisualizer

### ISSUE THREAD

**Issue by EstebanMonge** [nmonvisualizer/nmonvisualizer#10]
Hello:
I have a lot of questions, but one is very important.

We use nmonmerge to join daily files. NmonVisualizer can parse the file and some graphics works like a charm. But other doesn't.

The main reason for use nmonmerge is that we get a better performance vs parse each individual daily file.

For example in the GUI: Hostname->VM before the second day the graphics are break.

The situation is the same with:
Paging Amount
Page Faults

That are derived from all VM data. Do you have knowledge about this situation?

**Comment by hpresnall** [comment]
How much worse is the performance processing the files in NMONVisualizer? It could be related to garbage collection. Try setting the heap size larger (maybe `-Xmx2048M`, assuming you are on a 64 bit JVM). See if that helps. Also, how often do you have nmon collecting data - for a whole day of data, every 30 seconds is probably enough.

Regardless, can you post a screenshot of what the charts look like? Do you see the same issues when parsing the files in NMONVisuzalizer, without nmonmerge first?
