### ISSUE TITLE
Memory Usage by Component legend label

### ISSUE THREAD

**Issue by rowswell** [nmonvisualizer/nmonvisualizer#107]
Hi,

After loading nmon file(s) into the tool I click on the "Memory Use" tab which draws the graph for "Memory Usage by Component".  

On the left side of the graph the label shows "MB" - but I think this should be showing either "%" or "Percentage".   Do you agree?

Thanks
Dean

**Comment by hpresnall** [comment]
Yes, oops. It's an easy fix [here](https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/report/dataset_report.xml#L68) which I will do.

Just to confirm, are these values always between 0 and 100? If not, I'd need to make another change to ensure the Y axis isn't limited to that range.
