### ISSUE TITLE
Client Name can't be display when using NMONVisualizer command line to generate the chart files

### ISSUE THREAD

**Issue by minions167** [nmonvisualizer/nmonvisualizer#108]
Client Name can't be display when using NMONVisualizer command line to generate the chart files. If use GUI to generate those files, the full name of nmon client from the nmon file can be show complete. Please help. Thanks.

**Comment by hpresnall** [comment]
Do you mean the host name where the nmon file was collected?

Can you post screenshots of the issue?

**Comment by minions167** [comment]
Pls find the screen shot attached. The chart generated and save under GUI mode can show the full hostname while the cmd line couldn't. Thx. 
![IMG_20241230_140831](https://github.com/user-attachments/assets/5116ebea-9d11-4765-9c87-faa3e71e23a7)
![IMG_20241230_141055](https://github.com/user-attachments/assets/1e20898c-862a-4732-a0ee-d733acd62f5f)

**Comment by hpresnall** [comment]
This is most likely due to the size of the image file. The ReportGenerator defaults to a resolution of 1920x1080 which is not large enough to show the full hostname for each bar. If you resize the GUI do you see similar behavior?

I think there are 2 solutions:
1. Rename the hosts with shorter names - see https://nmonvisualizer.github.io/nmonvisualizer/renaming.html and use `-h <renaming_json>` on the command line
2. Change the default chart size here - https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/chart/definition/BaseChartDefinition.java#L27

If option 2 is required, I can add code that will accept a default chart resolution from the command line.

**Comment by minions167** [comment]
Sorry, I don't think the problem is due to size of image file as I use default setting and both of the image are 1920*1080 but the command line's result couldn't be shown while the GUI's result can be shown the full name automatically as seen in the attachment.

**Comment by minions167** [comment]
Both image have the same digits for hostname but the result of GUI will be automatically show as the full name.

**Comment by hpresnall** [comment]
I see the issue. Please try the fix and let me know if it looks ok using the command line.

I've also added optional `--width` and `--height` command line params in case you do want to change the image file sizes.

**Comment by minions167** [comment]
Many thanks and can you provide the jar file for testing as I can't find it. Thanks again.

**Comment by hpresnall** [comment]
Can you [build from source](https://github.com/nmonvisualizer/nmonvisualizer?tab=readme-ov-file#build-from-source)?

**Comment by minions167** [comment]
I have tried but failed to build it. Would you please help on this ? Sorry and many thanks.

**Comment by hpresnall** [comment]
[NMONVisualizer_2024-12-31.jar.zip](https://github.com/user-attachments/files/18279197/NMONVisualizer_2024-12-31.jar.zip)

Please unzip and run this jar file.

**Comment by minions167** [comment]
Dear hpresnall, it works. Thank you very much and may I know how to set the width, height, and also the output directory in the command line ? Many thanks.

**Comment by hpresnall** [comment]
When running the command line, just add something like `--width 2000 --height 1000` to change the size. Note that there is no way to change the font size, so at high resolutions, the text will be smaller. I think 1920 x 1080, default, should still work for most cases. Using host renaming to shorten the host names would also help.

The output directory is set to:
1. if there is only one path being parsed, the directory where the NMON files are located
2. or,  the current working directory (i.e. `pwd`) when you run the program
