### ISSUE TITLE
Process matching

### ISSUE THREAD

**Issue by jwickens** [nmonvisualizer/nmonvisualizer#11]
Hi I was wondering if it is possible to match a single or multiple process in the such as `<type name="<PID>">`? ie, something more specific than matching `<type name="$PROCESSES">`. This would be really useful for monitoring the more important processes.

**Comment by hpresnall** [comment]
Yes, that's possible with a custom chart. Something like this:

    <?xml version="1.0" encoding="UTF-8"?>
    <charts>
      <linechart name="CPU Utilization by Process" shortName="CPU by Process" linesNamedBy="TYPE">
        <yAxis label="% CPU" asPercent="true" />
        <data>
          <type regex="java \(.*\)" />
          <field name="%CPU" alias="% CPU" />
          
          <field name="% Processor Time" />
        </data>
        <data>
          <type regex="ksh \(.*\)" />
          <field name="%CPU" alias="% CPU" />
          
          <field name="% Processor Time" />
        </data>
      </linechart>
    </charts>


Save that and you can load if via `View -> Custom Report` in the GUI or with `-a` on the [command line] (http://nmonvisualizer.github.io/nmonvisualizer/commandline.html).

Note that you need a separate `<data>` element for each regex. You can also replace the regex attribute with `name` to match an exact process (e.g `name="foo (1234)"`). The regexes have escaped parens to avoid matching the aggregate process (e.g. `java`, without parens).

**Comment by jwickens** [comment]
Thank you, this is exactly what I was looking for. I actually wanted to match a familiy of processes at the aggregate level so my regex ended up looking like `foo.*[^\(.*\)]`
