### ISSUE TITLE
Nmon parsing error - DataType ERROR

### ISSUE THREAD

**Issue by luizlinux** [nmonvisualizer/nmonvisualizer#12]
Hello all.

First of all, great tool! Its about time someone stepped in and set us free from the MS Excell analyzer.

I just downloaded 30 nmon files from an AIX 7.1 server, but nmonvisualizer is not parsing them, any of them. I'm getting the same error for all files:
C:/path/to/file/servernmon.nmon:
SEVERE  could not parse C:/path/to/file/servernmon.nmon
java.lang.IllegalArgumentException: cannot redefine DataType ERROR within the same data set
	at com.ibm.nmon.data.DataSet.addType(DataSet.java:70)
	at com.ibm.nmon.parser.NMONParser.parseHeaders(NMONParser.java:240)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:80)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:137)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

It doesn't matter if I try to process one single file of all of them at once.
I have processed nmon files from several other AIX 7.1 servers, but this is the only server that this issue is occouring.

I appreciate any help.
I'm not sure if I could send you a "sample" nmon file from this server due to non-disclousure agreements and what not, unless you know a quick way to remove any sensible info from the nmon file.

Thanks folks.

**Comment by hpresnall** [comment]
Not sure what is 'sensitive' and what isn't. NMON definitely has the output of all the AIX system info programs (lsconf, lparstat -i, etc). The hostname is in multiple places as well; not sure about any IP addrs. If only the hostname is sensitive, you could search and replace that with a dummy value.

If that's not possible, then take a look at the NMON file. What that error indicates is that there are at least two lines that start with `ERROR`. Could you at least post a few lines before and after the ERROR lines?

**Comment by luizlinux** [comment]
Dude, you are simply awesome!

I 'greped' the file for lines starting with ERROR and guess what:
$ grep '^ERROR' servernmon.nmon
ERROR,T0000,errno=46 pathconf failed for /dev/cd0.
ERROR,T0000,errno=2 pathconf failed for /dev/asm/acfs_gg-96.

I removed those lines from the nmon file and nmnvisualizer processed it just fine. I guess I need to check that LPAR for those, probably defined and missing, devices.

Thanks a bunch, have a good one!

**Comment by hpresnall** [comment]
I am not sure why NMON is outputting those errors for missing paths after it's already output all the config data. That may be worth opening a defect against NMON; that might be an AIX PMR, but not sure.

If you want to try building a patched version of the tool, I just submitted a patch that will output a warning on these lines rather than bombing out.

**Comment by luizlinux** [comment]
Just built the patched version and the exception for the ERROR lines worked very nicelly. See screenshot attached.

Thank you very much for your incredibly prompt response!!
![2015-01-20_17-31-55](https://cloud.githubusercontent.com/assets/10618435/5824260/82513d84-a0ca-11e4-909a-1def56c07244.png)
