### ISSUE TITLE
Dates not recognized in format specified by documentation

### ISSUE THREAD

**Issue by jktrigg** [nmonvisualizer/nmonvisualizer#13]
java -jar ~/nmonvisualizer/NMONVisualizer_2014-12-11.jar com.ibm.nmon.ReportGenerator -s 2015-01-22T16:00:00X -e 2015-01-22T16:40:00X *
time specified for -s (2015-01-22T16:00:00X) is not valid

I have tried multiple variations of the ISO 8601 format (omitting non-alphanumeric characters, omitting seconds) and none have worked. What format do I need to use?

**Comment by hpresnall** [comment]
The SimpleDateFormat used for the times is `yyyy-MM-dd'T'HH:mm:ssX`. So, the time zone should be in digits. The following will work `2015-01-22T16:00:00-01`, `2015-01-22T16:00:00-0100` or `2015-01-22T16:00:00-01:00`. See the [JavaDoc]  (http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html).
