### ISSUE TITLE
Wrong hostname in charts

### ISSUE THREAD

**Issue by luizlinux** [nmonvisualizer/nmonvisualizer#14]
Ocasionally NmonVisualizer presents a different hostname on the charts than the real one as seen on the table view. I'm attaching screenshots of this error.
![2015-02-23_10-01-25](https://cloud.githubusercontent.com/assets/10618435/6328155/0c383948-bb43-11e4-92c9-b9528d22f9ea.png)
![2015-02-23_10-01-08](https://cloud.githubusercontent.com/assets/10618435/6328154/0c2b59e4-bb43-11e4-8020-f162c2c08929.png)

**Comment by luizlinux** [comment]
I found a way to fix this by choosing Options -> Name Systems -> By Nmon Run Name.
Any thoughts as to why I was getting different hostnames?

**Comment by luizlinux** [comment]
It seems its a Java redenring bug, somethign to do with the fonts I guess. When I resize the window I get the number 4 changed to 1, I'm atacheing screenshots of this weird behavior.

Sorry for misclosing this issue.

![2015-02-23_10-11-01](https://cloud.githubusercontent.com/assets/10618435/6328259/553d95b0-bb44-11e4-82c1-a58d4d047e2f.png)
![2015-02-23_10-10-44](https://cloud.githubusercontent.com/assets/10618435/6328258/553d7076-bb44-11e4-8364-3661761bc7b8.png)

**Comment by hpresnall** [comment]
This looks like a rendering bug. I can sometimes recreate it on my system. However, this is rendering done by JFreeChart, not by NMONVisuzalizer directly. I could possibly add an option to change the font, but I don't know if that's necessary for an intermittent bug like this.

Note that changing the naming method via Options -> Name Systems only changes the name if you set it _before_ any files are parsed.

**Comment by luizlinux** [comment]
Thanks for the reply. Whatever solution you come up with I'm sure it will be nice.
Perhaps you could give a heads up to the JFreeChart guys, this seems to be more on their side of the park than yours. ;)
