### ISSUE TITLE
Feature request: Stacked Area Graph for MEMNEW

### ISSUE THREAD

**Issue by luizlinux** [nmonvisualizer/nmonvisualizer#15]
Hi.

Title sais it all: Could the MEMNEW graph be changed to stacked area?
Another idea would be to add a stacked area MEMNEW tab to the summary(?) part of NmonVisualizer (shown in screenshot).

The point behind this is that people are more used to the stacked area graph that nmon analyser for Excell renders for MEMNEW. ;)

Appreciate it!
![2015-02-26_10-18-34](https://cloud.githubusercontent.com/assets/10618435/6392635/7cbafc9a-bda1-11e4-9d43-56a13864530a.png)

**Comment by hpresnall** [comment]
Easy enough - the last commit has something like what's in Excel.
If you don't want to do a custom build, you can load this as a custom report (View -> Custom Report). Here's the XML file:

    <?xml version="1.0" encoding="UTF-8"?>
    <charts>
      <linechart name="Memory Usage by Component" shortName="Memory Use" stacked="true">
        <yAxis label="MB" asPercent="true" />
        <data>
          <host os="AIX" />
          <type name="MEMNEW" />
          <field name="System%" alias="System" />
          <field name="FScache%" alias="File System" />
          <field name="Process%" alias="Processes" />
        </data>
      </linechart>
    </charts>
