### ISSUE TITLE
Warnings?

### ISSUE THREAD

**Issue by zwarmapapa** [nmonvisualizer/nmonvisualizer#16]
Why do I get these warnings when visualizing a couple of days worth of NMON data?

(the logs can be downloaded here: https://dl.dropboxusercontent.com/u/7174774/shares/other/nmon_logs.zip)

19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0098
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0098
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0098
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0112
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0112
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0112
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0112
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0112
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0154
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0154
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0154
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0154
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0154
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0061
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0061
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0061
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0061
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0061
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0005
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0005
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0005
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0005
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0005
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0019
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0019
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0019
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0019
19:49:08 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0019

**Comment by hpresnall** [comment]
What version are you using? I don't get those warnings when processing the files you provided.

Regardless, those warnings mean that some of the data from one file overlaps a record at the same time from another file. It each file has records from the same time, the first set of data won't be overwritten with the second. If you can process the files one by one to isolate this to two files, I can look further to confirm that this is a valid warning.

**Comment by zwarmapapa** [comment]
I use the jar from: http://dl.bintray.com/nmonvisualizer/NMONVisualizer/NMONVisualizer_2015-02-02.jar

It's quite weird that there are two or more overlapping records, since I run NMON only with a service which checks if NMON is already running or not. NMON keeps a record of every 5 minutes, for 30 days in total (currently it only has a couple of days of data), and it restarts the NMON process every 24 hours to ensure it is always running. It also stops/starts when I restart the server, since the process starts on startup. 

The init.d script I use for this can be found at: https://dl.dropboxusercontent.com/u/7174774/shares/other/nmon_init_d.txt

Crontab runs two things regarding NMON:
0  0  *  *  * /etc/init.d/nmon restart > /dev/null 2>&1
*/30  *  *  *  * /etc/init.d/nmon graph > /dev/null 2>&1

I hope this helps finding the cause of this problem.

**Comment by hpresnall** [comment]
One thing I notice is that in your init.d script you are running the ReportGenerator on the same directory that is being used for writing the current, *active* NMON file. It could by this was a transient error caused by the reporting program reading a partially complete NMON file. You may want to have nmon write to another location and use `/usr/share/nginx/nmon/logs` for storing completed logs.

I admit the overlap part of the merge code isn't well tested so if you can recreate this issue with just two files I can look some more.

**Comment by zwarmapapa** [comment]
Hmm, no luck. I tried turning off nmon (service nmon stop) and then visualizing the logs (service nmon graph), but it still gave a lot of warnings. I wonder, does the merging make a difference between days? Because it only says "not overwriting existing JFSFILE data at time THHMM", with HH and MM being hours and minutes?

**Comment by hpresnall** [comment]
My apologies, I wasn't looking at the full logs in the GUI when I processed this the first time. I *can* recreate this in both the GUI and the ReportGenerator.

These warnings are due to what looks like a bug in NMON. Grep your nmon logs for `JFS Filespace`:

    JFSFILE,JFS Filespace %Used lowentry-internal,/,/dev,/run,/,/run/lock,/run/shm

Note that /, the root fs, shows up 2x.

Internally, NMONVisualizer is putting the fields in a HashSet to compare one file's data to the other. This removes the extra / which has the side effect that the existing data now doesn't matching the new data and the program logs a warning. I have confirmed that data that's stored is the valid data, without the extra field for /. 

**You can safely ignore this warning.** However, it looks like you are using a very old version of NMON, 13g. Try upgrading to 14i and see if you are getting duplicate JSFFILE data for /.
