### ISSUE TITLE
Choose graphs to export using CLI

### ISSUE THREAD

**Issue by zwarmapapa** [nmonvisualizer/nmonvisualizer#17]
I only use 10 graphs that the NMON Visualizer creates, is it possible to choose which graphs the NMON Visualizer creates when using the command line interface, so it won't have to waste CPU/RAM on creating graphs that I don't use?

**Comment by hpresnall** [comment]
You can create a custom report XML file. If you just want to use a subset of the default reports, your best option is to get the standard [dataset_report.xml](https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/report/dataset_report.xml) and remove the charts you don't want.

Use the `--nodata` option on ReportGenerator to prevent the default charts and `-a` to specify your custom report XML.

**Comment by zwarmapapa** [comment]
Awesome, thanks!

**Comment by apolloj** [comment]
Hi, I want to have a lined-graph like "Idle Mem" % or "Idle cpu"%  (in place of CPU/Mem Utilization) Please, how can you do this ?

**Comment by hpresnall** [comment]
Something like this would work for memory idle (free).

    <linechart name="Memory Idle" shortName="Memory">
      <yAxis label="MB" />
      <data>
        <host os="UNIX" />
        <type name="MEM" />
        
        <field name="memfree" />
        
        <field name="Real free(MB)" alias="free" />
      </data>
      <data>
        <host os="PERFMON" />
        <type name="Memory" />
        <field name="Available MB" alias="Available" />
      </data>
    </linechart>

Note that this is the raw value, not the percentage. Transformations / calculations are not supported. There is an `asPercent` attribute for the y-axis, but it's for display; it does not do any calculations.

Similarly, for CPU, there is no idle value, only % used. So there's no way to graph %idle.
If you want to do calculations like that, you may need to output the raw CSV (`--rawdata`) or just the CSV for the data on each chart (`--chartdata`).

**Comment by apolloj** [comment]
Ok thanks for your quick reply, it's what I neeeded to know.
