### ISSUE TITLE
Load files on launch?

### ISSUE THREAD

**Issue by rhumpage** [nmonvisualizer/nmonvisualizer#18]
Is it possible to default which files to load into to the GUI when the jar is launched?   I would like to open/parse a directory at launch so the managers don't have to CTRL-O and decide which files to choose.  I know when there is a directory option for the CLI when creating the png files.  Tried to specify directory when launching GUI with no luck.  Thanks.

**Comment by hpresnall** [comment]
Try this latest commit. You can pass a list of files, directories or a combination; it will recursively search any directories for valid files. They will start processing as soon as the GUI loads.

**Comment by rhumpage** [comment]
Works great!  Thanks.
