### ISSUE TITLE
processing a directory

### ISSUE THREAD

**Issue by petepdx** [nmonvisualizer/nmonvisualizer#19]
nmon info
AIX 7.1.2
bos.perf.tools            7.1.2.15
command used to create nmon data file
/usr/bin/topas_nmon -m /var/stats/nmon -A -^ -l 512 -N -K -E -f -t -A -M -P -V -s10 -c60 -youtput_dir=/var/stats/nmon/sap7prp -ystart_time=00:00:01,Feb01,2015

A daemon copies the closed files in /var/stats/nmon to a Linux server 

For this pass, the data for all files created in Feb 2015 copied to a Linux server. Destination directory /data1/2015_2

Linux server
RHEL 7.1 Linux version 3.10.0-229.el7.x86_64 (mockbuild@x86-035.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-7) (GCC) ) #1 SMP Thu Jan 29 18:37:38 EST 2015

$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (rhel-2.5.4.7.el7_1-x86_64 u75-b13)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

NMONvisualizer info
NMONVisualizer_2015-02-02.jar 
command entered

The directory contains 4,032 files
java -jar NMONVisualizer_2015-02-02.jar com.ibm.nmon.ReportGenerator /data1/2015_2/sap7prp_150201_*
(144 files) No problems
2 days no problems

Then 3 days

/data1/2015_2/sap7prp_15020[123]_*

        /data1/2015_2/sap7prp_150203_0830.nmon... Complete
        /data1/2015_2/sap7prp_150203_0840.nmon... Complete
        /data1/2015_2/sap7prp_150203_0850.nmon... Complete
        /data1/2015_2/sap7prp_150203_0900.nmon... 08:24:14 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKAVGRIO data at time T0025
08:24:14 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKAVGRIO data at time T0025
08:24:14 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKAVGRIO data at time T0025
08:24:14 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKAVGRIO data at time T0025

Changing heap size doesn't seem to help, tried 256M, 512M, 1G

Data is available

-pete

**Comment by hpresnall** [comment]
For hundreds of files you may need to set the heap file to 2 GB or more. But, the indications of that are slow / stopped processing, not the errors your are seeing.

Do you have files from other systems that are also seeing issues on the 3rd day or just this system?
Do you get errors just processing the /data1/2015_2/sap7prp_150203_0900.nmon file?
