### ISSUE TITLE
Feature request: Top Process Bar Chart

### ISSUE THREAD

**Issue by luizlinux** [nmonvisualizer/nmonvisualizer#20]
Is it possible to have bar charts with "CPU% by command", "Memory by command (MBytes)" and " CharIO by command (bytes/sec)". Like the ones we get by using the Excell Nmon Analyser?

Thanks.

**Comment by hpresnall** [comment]
You can do this with a [custom report](http://nmonvisualizer.github.io/nmonvisualizer/customreports.html). Create an xml file with the following and you can load it via `View -> Custom Report` or the command line.

    <?xml version="1.0" encoding="UTF-8"?>
    <charts>
      <barchart name="%CPU by Process" shortName="Process %CPU" categoriesNamedBy="TYPE" barsNamedBy="STAT" stacked="true" subtractionNeeded="true">
      <yAxis label="% CPU" asPercent="true" />
      <data stat="AVERAGE">
        <type name="$PROCESSES" />
	<field name="%CPU">
      </data>
      <data stat="MAXIMUM">
        <host os="UNIX" />
        <type name="$PROCESSES" />
	<field name="%CPU">
      </data>
    </barchart>
    <barchart name="Memory by Process" shortName="Process Memory" categoriesNamedBy="TYPE" barsNamedBy="STAT" stacked="true" subtractionNeeded="true">
      <yAxis label="KB" />
      <data stat="AVERAGE">
        <type name="$PROCESSES" />
	<field name="Size">
      </data>
        <data stat="MAXIMUM">
          <host os="UNIX" />
          <type name="$PROCESSES" />
          <field name="Size">
        </data>
      </barchart>
    </charts>

**Comment by luizlinux** [comment]
Thanks Hunter! 

Your XML code worked flawlessly.

![2015-05-28_11-09-37](https://cloud.githubusercontent.com/assets/10618435/7862119/5c8df92e-052a-11e5-80cb-1215e691265f.png)
![2015-05-28_11-09-22](https://cloud.githubusercontent.com/assets/10618435/7862121/5deec9ce-052a-11e5-8f05-e77cbdee9a1d.png)

As a side note: Could you consider revamping the doc page on creating custom reports?
I mean, in a objective way the page is fine, but from my noob perspective it definitely needs more examples and a more textbook language/format.

Once again thank you so much.

**Comment by scbray1** [comment]
I have a lot of processes running. When I generate the "%CPU by Process" and "Memory by Process" charts I see too many columns and the names under the columns are too small to read. Is there a way of displaying only the top 10 processes ?
