### ISSUE TITLE
Does not work correctly with Java 8.

### ISSUE THREAD

**Issue by yustepanov** [nmonvisualizer/nmonvisualizer#23]
Hello!
NMONVisualizer does not work correctly with Java 8 on Mac.
If I try to manage time intervals, the screen becomes to look like puzzle and the application crashes after that. I do not have a similar problem with Java 7. 
Please correct the issue due to Java 8 is current version.

**Comment by hpresnall** [comment]
Can you give steps to reproduce this?

I have tried this with both the IBM and Oracle (1.8 U45) Java 8 versions and cannot recreate. What Java version (run `java -fullversion`) are you running?

**Comment by yustepanov** [comment]
Hello!

Now I use Java java full version "1.7.0_80-b15"
It was a cause why I stopped use Java 1.8U45
Mac OS X 10.10.3


With best regards,
Yuri Stepanov
yustepanov@yahoo.com

**Comment by yustepanov** [comment]
Hello!

Strange enough, but after installation of the lastest Java version (java full version "1.8.0_45-b14”) everything starts to work.

With best regards,
Yuri Stepanov
yustepanov@yahoo.com
