### ISSUE TITLE
Issue with NMON Visualiser

### ISSUE THREAD

**Issue by forsushilpotdar** [nmonvisualizer/nmonvisualizer#24]
Hi,

I am using the new version of NMON Visualiser. Tool is excellent!! But manytime it get hang during parsing the loaded file and we have to cancel the load of nmon files.
Please correct this bug.

Thanks
Sushil Potdar

**Comment by hpresnall** [comment]
Are you processing a large number of files or is each file very large? You may just be running out of memory.

Start the tool from the command line with something like `java -Xmx2048M -jar NMONVisuazlizer_xxx.jar`. This will give a max heap size of 2 GB. You can see how much memory is being used by going to the Help Menu and selecting Java Info - the last line will show total heap usage.

**Comment by forsushilpotdar** [comment]
Thanks hunter!!!
