### ISSUE TITLE
Per Process bugs

### ISSUE THREAD

**Issue by zwarmapapa** [nmonvisualizer/nmonvisualizer#25]
I don't know if this is from my nmon settings or from nmon visualizer, but I got a problem with the nmon graphs. 

Some processes aren't always on (like clamd for example), so they aren't in nmon, but the nmon visualizer doesn't seem to take that into account. Because of this, it often seems like clamd for example takes a lot of CPU on average, but in reality it only does this very briefly so its average CPU usage should be pretty low. 

Here are some graphs to see what I mean: http://internal.lowentry.com:5007/

Notice the CPU graphs and the most right memory graph as well. 

Nmon or the nmon visualizer doesn't seem to have anything in place for when a process isn't running, meaning it doesn't understand that CPU/RAM usage at those points is 0. 

Because of this, the line graph doesn't make sense, and the CPU and memory per process bar graph is incorrect (unless it is CPU and memory per process while running of course). 

If there is no solution for this in nmon, which there isn't as far as I currently know, could you look into it?

**Comment by zwarmapapa** [comment]
Some additional info:

The XML it uses can be found here: http://internal.lowentry.com:5007/dataset_report.xml

NMON captures every 10 seconds

It updates the graphs every day around 02:00 server time

**Comment by hpresnall** [comment]
It's not your configuration. Missing values were being skipped when calculating statistics. The latest commit fixes this for process data. Please try out this fix and let me know if it's reporting how you expected.

I am not 100% sure this is correct for anything other than CPU however since memory and other values are not 0 when there is no data. Any thoughts on how to handle this better?

**Comment by zwarmapapa** [comment]
Hmm, I've updated to the last branch, ant compiled it, and updated the graphs, but it doesn't seem to be fixed: http://internal.lowentry.com:5007

I've made a script that automatically git pulls the latest NMON Visualizer, ant compiles it, and updates the graphs, so you can iterate quickly on it if you want to. Also made a script to see the log files NMON Vizualizer uses and creates. 

You can run the update script by going to: http://internal.lowentry.com:5007/update.php

You can see the NMON logs used, as well as the output log of NMON Visualizer, at: http://internal.lowentry.com:5007/logs/

Let me know when you're done so I can delete the scripts. 

About the memory thing, I don't know how you read the data, so there's not much I can suggest that would make sense. I would try something like keeping track of every process read, and then during every nmon process memory 'snapshot' read add 0 values to every process that is not in that 'snapshot'.

**Comment by hpresnall** [comment]
Ok good. Confirmed it's working for me with your data as well.

For the line graph, I'd rather leave it as it. No data, no line.
Note that in the chart you have up now, the line for clamd and php5-fpm look similar and cross over each other - http://internal.lowentry.com:5007/graphs/CPU%20by%20Process.png.

**Comment by zwarmapapa** [comment]
I think that's clamd and java btw :P

But yeah, the thing that looks weird is freshclam for example, which looks like its taking 30%-40% at all times, which is of course not the case. This gives a false image of that freshclam takes a lot of CPU. 

Anyway, I don't really mind it too much, you just have to be a bit skeptical when you're looking at the line graph.
