### ISSUE TITLE
incorrect DISKXFER display

### ISSUE THREAD

**Issue by putnik2000** [nmonvisualizer/nmonvisualizer#28]
I compare output from Visualizer and Analyzer and for DISKXFER Analyzer shows the hdisk behavior that I have seen by eyes on working system, but the Visualizer shows completely zero activity for those particular disks. I can send screenshots and nmon source if needed.

**Comment by putnik2000** [comment]
![2015-10-23 19-29-52 nmon visualizer - test1 12 00 00 21 - 18 00 00 21](https://cloud.githubusercontent.com/assets/958655/10699004/7bb36878-79bc-11e5-8bd4-347f02bae8e0.png)

**Comment by putnik2000** [comment]
![2015-10-23 19-30-53 aix1_21-oct-2015_1204_to__ nmon xlsx - excel](https://cloud.githubusercontent.com/assets/958655/10699034/ad4a7bc4-79bc-11e5-8d59-e27b13cd8ca5.png)

**Comment by hpresnall** [comment]
Sorry I somehow missed this. Do you still see this issue?
The screenshots you posted showed `DISKWRITE` in NMONVisualizer and `DISKXFER` in Excel.

**Comment by putnik2000** [comment]
Hi! That was once in one of my projects, so I might have missed that
particular case. In case I find it again - I will let you know, close for
now, thank you)

2015-12-17 18:22 GMT+03:00 Hunter Presnall <notifications@github.com>:

> Sorry I somehow missed this. Do you still see this issue?
> The screenshots you posted showed DISKWRITE in NMONVisualizer and DISKXFER
> in Excel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nmonvisualizer/nmonvisualizer/issues/28#issuecomment-165482046>
> .
>



-- 
Regards

Nikita Yaskevich
putnik2000@gmail.com
