### ISSUE TITLE
nmon visualiser stopped analyse at 15th nmon files 

### ISSUE THREAD

**Issue by finas83** [nmonvisualizer/nmonvisualizer#29]
Dear nmon visualizer,

need great help. my nmon file stopped analyse at 15th nmon files.
I need to analyse minimum 30 nmon files in one go if possible.
Many thanks. 
![nmon visualiser](https://cloud.githubusercontent.com/assets/16110362/11520112/1de90264-98db-11e5-9915-0a192ddd43fd.jpg)

**Comment by hpresnall** [comment]
Most likely, you have run out of memory. Try running from the command line with something like `java -Xmx2048M -jar NMONVisualizer.jar`. You may need an even higher -Xmx value if your files are very large.

**Comment by finas83** [comment]
Dear Mr Presnall,

Many thanks for great help. It works.

need great advise, in addition to average CPU, how can I add the maximum
CPU utilisation in the same graph.
Hope to hear from you. Many thanks.

**Comment by hpresnall** [comment]
Use a custom report with something like the following XML. You can load it via `View -> Custom Report`. Then `File -> Load` in the custom report dialog.

    <?xml version="1.0" encoding="UTF-8"?>
    <charts>
      <barchart name="Average CPU Utilization" shortName="CPU" stacked="true" categoriesNamedBy="HOST" barsNamedBy="STAT" subtitledBy="NONE">
        <yAxis label="% CPU" asPercent="true" />
        <data stat="AVERAGE">
          <host os="UNIX" />
         <type name="CPU_ALL" />
          <field name="CPU%" />
        </data>

        <data stat="MAXIMUM">
          <host os="UNIX" />
          <type name="CPU_ALL" />
          <field name="CPU%" />
        </data>
      </barchart>
    </charts>

**Comment by finas83** [comment]
Dear Mr Presnall Many thanks
where could I put the XML coding?

Many thanks,

**Comment by hpresnall** [comment]
You can save it anywhere on the file system. Load it as a custom report.
View -> Custom Report opens a new custom report window. Then File -> Load in that window.
