### ISSUE TITLE
Missing disk devices 

### ISSUE THREAD

**Issue by lmassars** [nmonvisualizer/nmonvisualizer#30]
When parsing NMON file collected on RHEL 6.6 (nmon-14g-1.el6.rf.x86_64) NMONVisualizer truncates approx. half of the disk devices in "Disk Writes" and "Disk Reads" tabs thus disk statistics data is missing.

**Comment by hpresnall** [comment]
Is it truncating the disk names are is it not displaying 1/2 the disks?
Can you give examples of disk names that are having this issue?

**Comment by lmassars** [comment]
Hi, I have these DDN SFA block devices and multipath devices that NMON collects information for, and I can see them in .nmon file (see DISKWRITE and DISKWRITE1 below).
When I load .nmon files and Visualizer parses it, I can only see devices up to sddf in Disk Write tab, so it looks like it's not picking up any device from DISKWRITE1 list (see the capture png below).
The list of devices under the graph also stops at device sddf.

![capture](https://cloud.githubusercontent.com/assets/16359287/11915021/9d0865e6-a662-11e5-9677-9fa62ce23ab6.PNG)

DISKWRITE,Disk Write KB/s plinfo-uddn02-nsd01,sda,sda1,sda2,dm-0,dm-1,dm-2,dm-3,sdb,sdc,sdd,sde,sdf,sdg,sdh,sdi,sdj,sdk,sdl,sdm,sdn,sdo,sdp,sdq,sdr,sds,sdt,sdu,sdv,sdw,sdx,sdy,sdz,sdaa,sdab,sdac,sdad,sdae,sdaf,sdag,sdah,sdai,sdaj,sdak,sdal,sdam,sdan,sdao,sdap,sdaq,sdas,sdar,sdau,sdat,sdav,sdaw,sdax,sday,sdaz,sdba,sdbb,sdbc,sdbd,sdbe,sdbf,sdbg,sdbh,sdbj,sdbi,sdbk,sdbl,sdbm,sdbn,sdbo,sdbq,sdbr,sdbp,sdbt,dm-4,sdbu,sdbs,sdbv,sdbw,sdby,sdbx,sdbz,sdca,sdcb,sdce,sdcd,sdcc,sdcg,sdch,sdcj,sdci,sdck,sdcf,sdcl,sdcm,sdcn,sdcq,sdco,sdcp,sdcr,sdcs,sdct,sdcu,sdcv,sdcw,sdcy,sdcx,sdcz,sdda,dm-5,dm-6,dm-7,dm-8,dm-9,dm-10,dm-11,dm-12,dm-13,dm-14,dm-15,dm-16,dm-17,dm-18,dm-19,dm-20,dm-21,dm-22,dm-23,dm-24,dm-25,dm-26,dm-27,dm-28,dm-29,dm-30,dm-31,dm-32,dm-33,dm-34,dm-35,dm-36,dm-37,sddb,sddc,sddd,sdde,sddf
DISKWRITE1,Disk Write KB/s plinfo-uddn02-nsd01,sddg,sddh,sddi,sddj,sddl,sddm,dm-38,sddn,sddk,sddp,sddo,sddq,sdds,sddr,sddt,sddv,sddw,sddu,sddy,sddx,sdea,sddz,sdeb,sded,sdec,sdee,sdef,sdeg,sdeh,sdei,sdek,sdel,sdej,sden,sdem,sdeo,sdeq,sder,sdep,sdet,sdeu,sdev,sdew,sdex,sdes,sdey,sdez,sdfa,sdfc,sdfb,sdfd,sdfe,sdff,sdfh,sdfg,sdfj,sdfi,sdfk,sdfl,sdfn,sdfm,sdfo,sdfp,sdfr,sdfq,sdfs,sdft,sdfu,sdfv,sdfw,sdfx,sdfy,sdfz,sdga,sdgb,sdgd,sdgc,sdge,sdgf,sdgg,sdgh,sdgi,sdgj,sdgk,sdgl,sdgm,sdgn,sdgo,sdgp,sdgq,sdgr,sdgt,sdgs,sdgu,sdgv,sdgw,dm-39,sdgy,sdgx,sdgz,sdha,dm-40,dm-41,dm-42,dm-43,dm-44

**Comment by hpresnall** [comment]
So this is actually a filter that is part of the data set report. The disk charts in the tabs only show the sda, hda, vda and dasd disks - no partitions, dm volumes or anything else. The assumption was that you could always trace back to the base disk if you had SAN LUNs, etc.

The data should still be there if you expand the system on the left hand nav and look at the raw DISKWRITE charts. You could also create a custom chart with just the disks you wanted in it.

**Comment by lmassars** [comment]
Yes, thank you. I see it now in the expanded list. Can I ask you, I am trying to merge disk stats from different servers into an aggregated disk stats, let's say I have 8 servers that support parallel filesystem and I'd like to aggregate IOPS and throughput from all 8 to get a complete picture. What's the best way to do this? I loaded two of the servers and tried to merge server2 into server1 but the tool is now not responsive, it's been like this for about last 15 minutes. Is there a better way to do the data merge?
And another question I have, if I create diskgroups with NMON will Visulaizer support and display stats for the groups? For example, separate disk groups for flash and spinning devices.
Thanks you!
Leo

**Comment by hpresnall** [comment]
The merge probably failed because you ran out of JVM heap. You could try setting -Xmx from the command line. However, if you are merging datasets with data from the same time range, any disks with the same name will be overwritten. So, that may not be what you want.

I haven't used disk groups. But, if it creates a separate disk name or a new data type it should show up in the tool.

Your best option would be to create a custom report XML file. Something like this should work:

    <charts>
    <linechart name="Total Disk Writes" shortName="Disk Writes" stacked="true" linesNamedBy="HOST_FIELD">
      <yAxis label="KB / s" />
      <data>
        <host name="system1" />
        <type name="DISKWRITE" />
        <field name="sda1" />
      </data>
      <data>
        <host name="system2" />
        <type name="DISKWRITE" />
        <field name="sdb1" />
      </data> 
    </linechart>
    </charts>

Just add new `<data>` element for each system and specify the disks you want from each one. You can specify multiple `<type>` fields if you need more than one disk from a system or even something like `<field regex="plinfo.*">`.

**Comment by lmassars** [comment]
Thank you for your help with this! Appreciate it. Happy Holidays!

**Comment by lmassars** [comment]
Sorry, one more question. I tried to open custom xml report but received invalid file (please see attached)
![report](https://cloud.githubusercontent.com/assets/16359287/11916217/133b0e98-a69b-11e5-8981-e2a68f561f2e.PNG)

Below is custom.xml

<?xml version="1.0" encoding="UTF-8"?>
<charts>
<linechart name="Total Disk Writes" shortName="Disk Writes" stacked="true" linesNamedBy="HOST_FIELD">
  <yAxis label="KB / s" />
  <data>
    <host name="plinfo-uddn02-nsd01" />
    <type name="DISKWRITE" />
    <field name="sddz" />
  </data>
  <data>
    <host name="plinfo-uddn02-nsd02" />
    <type name="DISKWRITE" />
    <field name="sddz" />
  </data> 
</linechart>
</charts>

Thank you.

**Comment by lmassars** [comment]
<charts>
<linechart name="Total Disk Writes" shortName="Disk Writes" stacked="true" linesNamedBy="HOST_FIELD">
  <yAxis label="KB / s" />
  <data>
    <host name="plinfo-uddn02-nsd01" />
    <type name="DISKWRITE" />
    <field name="sddz" />
  </data>
  <data>
    <host name="plinfo-uddn02-nsd02" />
    <type name="DISKWRITE" />
    <field name="sddz" />
  </data> 
</linechart>
</charts>

**Comment by lmassars** [comment]
custom.xml is attached below

![custom](https://cloud.githubusercontent.com/assets/16359287/11916233/74b60cae-a69b-11e5-9ebd-2d9dcb039f36.PNG)

**Comment by hpresnall** [comment]
Not sure why that's happening. I recreated what you posted and it works for me.

Bring up the log (Help -> View Log or CTRL-L) and you should be able to see what the error is. You can also turn up the level to FINEST and she how far the parse gets.

**Comment by lmassars** [comment]
Nothing comes up in the log even when I set to level FINEST. What's the proper procedure to load customer report? First load .nmon file, then View ->Customer Report, then Load in the new window and choose .xml file? It's strange but Parse Report XML window does not even pick up custom.xml in the current directory and I have to type in the file name every time.

**Comment by lmassars** [comment]
Ok, I just changed directories in Parse Report XML window back and forth and it did recognize report.xml but now I am getting a different parse error.
![capture](https://cloud.githubusercontent.com/assets/16359287/11920311/76422776-a739-11e5-9e40-bc41312efad6.PNG)

**Comment by lmassars** [comment]
I got it partially working. Still getting the error.
![capture](https://cloud.githubusercontent.com/assets/16359287/11920414/15955098-a73d-11e5-8761-1ebba2519b06.PNG)

![script](https://cloud.githubusercontent.com/assets/16359287/11920417/31a65192-a73d-11e5-958a-c82ed1d9fcbe.PNG)

**Comment by hpresnall** [comment]
There must be some other issue. The XML looks correct. Can you upload a copy of the file somewhere?

**Comment by lmassars** [comment]
I think I am on the right track now as I am adding DISKWRITE and DISKREAD data for each server. The xml file is becoming very long though. One question, since I have same disk names on each of the 8 servers I have to use linesNamedBy="HOST_FIELD" but the graph portion of each chart becomes very busy because each disk name is prepended by the long server name. Is there a way to drop the disk names from the graph and only leave them in the table below the graph?

![capture](https://cloud.githubusercontent.com/assets/16359287/11921041/f9dee368-a74c-11e5-8974-c9049ee91a59.PNG)

This is my xml file so far:
- <charts>
- <linechart name="SSD Disk Writes" shortName="Disk Writes" stacked="true" linesNamedBy="HOST_FIELD">
  <yAxis label="KB / s" /> 
- <data>
  <host name="plinfo-uddn02-nsd01" /> 
  <type name="DISKWRITE" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd01" /> 
  <type name="DISKWRITE1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd02" /> 
  <type name="DISKWRITE" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd02" /> 
  <type name="DISKWRITE1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd03" /> 
  <type name="DISKWRITE" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd03" /> 
  <type name="DISKWRITE1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd04" /> 
  <type name="DISKWRITE" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd04" /> 
  <type name="DISKWRITE1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
  </linechart>
- <linechart name="SSD Disk Reads" shortName="Disk Reads" stacked="true" linesNamedBy="HOST_FIELD">
  <yAxis label="KB / s" /> 
- <data>
  <host name="plinfo-uddn02-nsd01" /> 
  <type name="DISKREAD" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd01" /> 
  <type name="DISKREAD1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd02" /> 
  <type name="DISKREAD" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd02" /> 
  <type name="DISKREAD1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd03" /> 
  <type name="DISKREAD" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd03" /> 
  <type name="DISKREAD1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd04" /> 
  <type name="DISKREAD" /> 
  <field name="sdbn" /> 
  <field name="sdbo" /> 
  <field name="sdbp" /> 
  <field name="sdbq" /> 
  <field name="sdbr" /> 
  <field name="sdbs" /> 
  <field name="sdbt" /> 
  <field name="sdbu" /> 
  </data>
- <data>
  <host name="plinfo-uddn02-nsd04" /> 
  <type name="DISKREAD1" /> 
  <field name="sdfn" /> 
  <field name="sdfo" /> 
  <field name="sdfp" /> 
  <field name="sdfq" /> 
  <field name="sdfr" /> 
  <field name="sdfs" /> 
  <field name="sdft" /> 
  <field name="sdfu" /> 
  </data>
  </linechart>
  </charts>

**Comment by lmassars** [comment]
xml didn't paste correctly...

**Comment by lmassars** [comment]
let me send it as attachment in reply.

**Comment by lmassars** [comment]
[charts.docx](https://github.com/nmonvisualizer/nmonvisualizer/files/67997/charts.docx)

See if you can open this word attachment with xml script.

**Comment by hpresnall** [comment]
The legend is going to get busy with that many disks. Unfortunately, the name for each line has to be unique, so the hostname or something else needs to be there.

Keep in mind you can rename the host to something shorter by specifying a JSON file to Options -> Name Systems -> By custom file  -- see http://nmonvisualizer.github.io/nmonvisualizer/renaming.html.

Another option you could use separately or combine with host renaming is to give each disk an alias. Like `<file name="sdbn" alias="n" />`. It's not much, but that may help.

The good news is that if you have the same disks on every system, you can simplify the XML to this:

    <charts>
      <linechart name="SSD Disk Writes" shortName="Disk Writes" stacked="true" linesNamedBy="HOST_FIELD">
        <yAxis label="KB / s" />
        <data>
          <type regex="DISKWRITE.*" />
          <field name="sdbn" alias="n" />
          <field name="sdbo" alias="o" />
          <field name="sdbp" alias="p" />
          <field name="sdbq" alias="q" />
          <field name="sdbr" alias="r" />
          <field name="sdbs" alias="s" />
          <field name="sdbt" alias="t" />
          <field name="sdbu" alias="u" />
        </data>
      </linechart>
      </charts>


Note, drop the `<host>` (i.e. match all hosts) and use a regex on the type.

Finally, if you want to just sum the disks for each host and only have one line for that host, you could add `stat=SUM` to `<data>` and change `linesNamedBy=HOST_STAT`.

**Comment by lmassars** [comment]
Thank you for suggestions. I stuck on a different challenge now. Few servers report multipath dm- devices instead of sd and when I create a report for them nothings comes up even though I can see their non-zero stats when expand the server tree in default window and look for DISKREADS1 for example.
The last line in the log says "reduced 1 charts to 0 for data ..."
[charts.docx](https://github.com/nmonvisualizer/nmonvisualizer/files/68086/charts.docx)

**Comment by lmassars** [comment]
![capture](https://cloud.githubusercontent.com/assets/16359287/11923157/7f86aa1c-a76d-11e5-8cbc-f61e884f442f.PNG)

**Comment by hpresnall** [comment]
Can you do something similar and just specify the fields explicitly for the dm devices? Like ` <field name="dm-11" alias="11" />`.
