### ISSUE TITLE
Parsing error on nmon v9 files

### ISSUE THREAD

**Issue by yleg** [nmonvisualizer/nmonvisualizer#31]
Hi,
It seems impossible to analyze old nmon version records. Tests with nmon v9a for AIX 4.3x or AIX 4.2x leads systematically to the same error in Nmon Visualizer, whatever the version of visualizer used :

SEVERE  could not parse ... file.nmon
java.lang.IndexOutOfBoundsException: start 1, end 0, s.length() 1
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at com.ibm.nmon.parser.NMONParser.parseBBBP(NMONParser.java:431)
	at com.ibm.nmon.parser.NMONParser.parseHeaders(NMONParser.java:181)
	at com.ibm.nmon.parser.NMONParser.parse(NMONParser.java:80)
	at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:137)
	at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
	at java.lang.Thread.run(Unknown Source)

An example of nmon v9 file is attached.
[aix433.txt](https://github.com/nmonvisualizer/nmonvisualizer/files/78557/aix433.txt)

**Comment by hpresnall** [comment]
I am sure there is an amazing story behind why you are still running AIX 4.3 :) Haven't seen that in a long time.

The good news is that the fix to support this was minor. You can pull the latest code and build NMONVisualizer to pick that up. Or, you could just delete the BBBP section from your files completely.

In either case, it appears that the CPU_ALL header isn't in this file either. This will causing warnings about undefined data and you won't get a CPU graphs in the tabbed report views. If you want to fix that, you will need to add a line like `CPU_ALL,CPU Total,User%,Sys%,Wait%,Idle%,Busy,PhysicalCPUs` _after_ the AAA records.

**Comment by yleg** [comment]
Thanks very much for your answer, the fix is OK.
"Amazing" wouldn't be the right term to describe that AIX 4.3 story, I think "long" would be more appropriate :) There's an adage in french civil aviation administration, which says "if it works, don't touch it...".
