### ISSUE TITLE
Help with the most simple xml file you ever heard of :-)

### ISSUE THREAD

**Issue by thsnielsen** [nmonvisualizer/nmonvisualizer#33]
looks really good, i like the GUI - but i have many files to process.
For a limited number of hosts, i have an nmon file each day, and i would like to make a graph over ONE number in the nmon data - screenshot attached

![nmonvisualizer](https://cloud.githubusercontent.com/assets/16719354/12353444/99c7c98e-bb8f-11e5-84dc-e9c712b43a58.png)

, and i see that the command line make a continous graph when the nmon files are continous - very good.
This is the xml i tried to make :  
cat ndsdResData.xml 
\<linechart name="NDSD ResData" shortName="NDSD" stacked="true"\>
  \<yAxis label="NDSDResdata" asPercent="false" /\>
  \<data\>
    \<host os="linux" />
    \<type name="TOP" />
    \<field name="ndsd" />
    \<field name="ResData" />
  \</data>
\</linechart>

What i want is a graph of <host>,TOP,ndsd<PID>,ResData for each host, collecting the values from all my nmon files for that host - like it does in the standard run if i do : 
 java -jar NMONVisualizer_2015-10-21.jar com.ibm.nmon.ReportGenerator 20160112/slz852* 

btw i also have problems getting the -mf accepted

 by the command line (maybe i need to use -d?) i have tried variations of (placing the mf before and after various places :-): 
java -jar NMONVisualizer_2015-10-21.jar com.ibm.nmon.ReportGenerator 20160112/slz852* -mf ndsdResData.xml 

Any help greatly appreciated :-) do not hesitate to ask me questions, if i did not explain well.

**Comment by hpresnall** [comment]
Documentation bug - it should be `--mt` or `--mf`. I will fix that. However you don't need to multiplex by type unless you wan to get ResData for all the processes on each system.

Instead you just want to use `-d` to create a chart per hostname or `-a` to create one chart that has a line for each host. (If you want to use -a, you will need to add `linesNamedBy="HOST"` to the `<linechart>` element below.)

On your chart definition, you need to specify the type as ndsd like this:

    <?xml version="1.1" encoding="UTF-8"?>
      <charts>
        <linechart name="NDSD ResData" shortName="NDSD">
          <yAxis label="NDSDResdata" />
          <data>
            <host os="linux" />
            <type name="ndsd" />
            <field name="ResData" />
          </data>
        </linechart>
    </charts>

Note that this assumes you only have a single ndsd process on each host. If you have more than one process then the type named `ndsd` is actually the sum of the process data values for all the ndsd processes running.

**Comment by thsnielsen** [comment]
Thank you for your reply - that helped me progress a lot.
However (and sorry to pull off the arm when when you propose a hand) i am one step from perfect, and i would really like (another hand :-) to get there.
As you can see below, i have 3 ndsd processes one without PID, and two others with PID in brackets. I would the ResData for all three of them in the same chart.
Now if this gets complicated, just tell me, and i will stick with what i have it is already good, but if it is "simple" i would like to know.
Here my current xml file : 
cat ndsdResData.xml 
\<?xml version="1.1" encoding="UTF-8"?>
\<charts>
  \<linechart name="NDSD ResData" shortName="NDSD" linesNamedBy="HOST" >
    \<yAxis label="NDSDResdata" />
    \<data>
      \<host os="linux" />
      \<type regex="ndsd*" />
      \<field name="ResData" />
    \</data>
  \</linechart>
\</charts>

Here how my data looks like
![nmonvisualizer](https://cloud.githubusercontent.com/assets/16719354/12452246/bd2e32c6-bf8d-11e5-8982-36aff5c8893a.png)

**Comment by hpresnall** [comment]
Change `linesNamedBy` to `TYPE` and set the regex to `ndsd.*`;dot star - it's a regex, not a glob that always gets me too.

Note that the ndsd process without a number is the sum of _all_ the ndsd processes. If you care about the total value, this may be all you need.

You may also just want a stack chart with all the processes on it (minus the overall ndsd process). To do that, add `stack=true` to the `<linechart>` element and change the `<type>` element to `<type regex="java \((.*)\)" aliasByGroup="1" />`. That type definition finds only java processes with parens and uses group 1 of the regex as the name on the chart.

**Comment by thsnielsen** [comment]
you rock !!  Thanks a million, now i have exactly what i need, and a reasonable idea on howto  change the xml for future needs.
Here for others what ended up doing : 
java -jar NMONVisualizer_2015-10-21.jar com.ibm.nmon.ReportGenerator 20160112/* -a ndsdResData.xml 

with 

cat ndsdResData.xml 
\<?xml version="1.1" encoding="UTF-8"?>
\<charts>
  \<linechart name="NDSD ResData" shortName="NDSD" linesNamedBy="HOST" >
    \<yAxis label="NDSDResdata" />
    \<data>
      \<type regex="ndsd.*" />
      \<field name="ResData" />
    \</data>
  \</linechart>
\</charts>

which gives : 
![ndsd](https://cloud.githubusercontent.com/assets/16719354/12482818/058a8956-c052-11e5-9058-1bb549b3d746.png)

exactly what i needed - THANK YOU :-)

**Comment by hpresnall** [comment]
FYI, you are naming by host but selecting multiple ndsd processes. What's being graphed is `one` of the ndsd processes on each how. Which one is somewhat random based on how the data is hashed internally.

If you want to graph all the processes on all the hosts change the linesNamedBy to `HOST_TYPE`. If you only want to graph the overall ResData, set the type element to just `<type name="ndsd">`.
