### ISSUE TITLE
hello !i need some help .thanks

### ISSUE THREAD

**Issue by tianxia007** [nmonvisualizer/nmonvisualizer#34]
how to set the last arg?
web003160306
java -jar NMONVisualizer_2016-02-29.jar com.ibm.nmon.ReportGenerator web003_160305_1107.nmon /web003160306

**Comment by hpresnall** [comment]
You want to parse one file, web003_160305_1107.nmon, and then everything in the web003160306 directory? That should work.

If the file is in that directory, you can just specify the directory and all the files in the directory will be recursively parsed.
