### ISSUE TITLE
WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data

### ISSUE THREAD

**Issue by lmassars** [nmonvisualizer/nmonvisualizer#35]
Hi, I am running report generator merging multiple csv files on Windows 8.1 and getting these warnings after processing about 10 csv files:

> java -Xmx1480m -jar ..\NMONVisualizer_2016-02-29.jar com.ibm.nmon.ReportGenerator *

18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0039
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0039
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0039
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0097
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0030
18:23:42 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing JFSFILE data at time T0180

**Comment by lmassars** [comment]
Parsing NMON files...
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_02240100.csv... Complete
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_02250100.csv... Complete
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_02260100.csv... Complete
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_02270100.csv... Complete
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_02280100.csv... Complete
        C:\Users\g2ulym\Desktop\LE\plgrid-uibx02-1a.nmon_03010100.csv... 18:39:15 WARNING com.ibm.nmon.data.SystemDataSe
t.mergeDataForType: not overwriting existing DISKBSIZE data at time T0025
18:39:15 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKBSIZE data at time T0025

18:39:15 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKBSIZE data at time T0025

18:39:15 WARNING com.ibm.nmon.data.SystemDataSet.mergeDataForType: not overwriting existing DISKBSIZE data at time T0025

**Comment by lmassars** [comment]
Hello, is there anyone who can provide a solution for this?

**Comment by hpresnall** [comment]
These are warnings. It indicates that the files you are merging already have data for that type (JFSFILE) at the given timestamps. It will ignore the data from later files.
