### ISSUE TITLE
How to parse Windows Perfmon & ESXTop data (exported to CSV)

### ISSUE THREAD

**Issue by PriyankaGuptaAcc** [nmonvisualizer/nmonvisualizer#36]
Hi,
Please help me with the command line commands to parse Windows Perfmon & ESXTop data (exported to CSV) file to nmonvisualizer  and hence generate the charts and analysis reports.

**Comment by PriyankaGuptaAcc** [comment]
![error](https://cloud.githubusercontent.com/assets/18695112/14846890/9c46a2ee-0c83-11e6-8850-271d323652c7.jpg)

**Comment by hpresnall** [comment]
Do you have something stripping out extra `\` in the CSV? The parser is expecting something like `\\hostname\category (optional subcategory)\metric`.

Just tested on Win 10 by setting the Log Format to Comma Separated and Binary. I parsed the Binary log with `relog -f csv foo.blg -ofoo.csv`
