### ISSUE TITLE
Not able to parse iostat output

### ISSUE THREAD

**Issue by vikaasbv** [nmonvisualizer/nmonvisualizer#40]
I have a log capture from IOSTAT from a Linux system captured using the options "-dxt", which is not getting parsed.

The error reported is pasted below

16:38:03 SEVERE com.ibm.nmon.gui.file.ParserRunner.run: could not parse 

java.io.IOException: duplicate header for 10/10/2016 at line 51
    at com.ibm.nmon.parser.IOStatParser.parseDataTypes(IOStatParser.java:388)
    at com.ibm.nmon.parser.IOStatParser.parse(IOStatParser.java:107)
    at com.ibm.nmon.NMONVisualizerApp.parse(NMONVisualizerApp.java:160)
    at com.ibm.nmon.gui.file.ParserRunner.run(ParserRunner.java:73)
    at java.lang.Thread.run(Unknown Source)

[iostat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/521652/iostat.zip)

**Comment by hpresnall** [comment]
What version of the sysstat package are you running? I am running 11.2.0 on ubuntu 16.04 and it doesn't work either. It appears that IOStat has changed their output format (again) at some point.

I will look at updating for 11.2.0 version but am not sure I want to maintain backwards compatibility.

**Comment by hpresnall** [comment]
Actually, I realized I have a bug here. The time has to be in ISO format or it fails to find subsequent timestamps.

Try `export S_TIME_FORMAT=ISO` before running iostat.

**Comment by hpresnall** [comment]
Current version requires ISO time format.
It may be possible to update existing files with another shell script but I haven't attempted this.
