### ISSUE TITLE
graphs don't match numbers

### ISSUE THREAD

**Issue by darbyj22** [nmonvisualizer/nmonvisualizer#42]
First off, I love this application. I've been using the nmon_analyzer in excel and it's been a pain. I was looking for something that I could put a month of data into and get some graphical representation. I've noticed though that the graphs don't actually match the numbers but only when I'm loading multiple days of data. Example. a single day might show me a peak of 60-70% usage but when I load multiple days, the graph never seems to go above 50% or so for that day. Let me know if you need examples or if you think I"m doing something wrong. Thanks!

**Comment by flyisland** [comment]
I guess I encounter the same issue.

I load just one day data in, and check with the "CPU by process" tab. It shows that the Max cpu% of the `java` process is **25%**

, but the realted line in the graph is never higher than 10%. So I can not find out when exactly the peak time is of this `java` process.

**Comment by ikoskin** [comment]
I think this is a feature of displaying the average value. If you reduce the time range of displaying the graph, for example, one hour, then you will see your maximum value on the graph.

**Comment by Lt0001us1** [comment]
we are experiencing the graphs showing an avg instead of MAX points & we NEED MAX points to identify with our internal customers where the work load is real time MAX, not avg. yes, by reducing the time frame, the MAX is more displayed, however, we need MAX over 8 PLUS hours of data, any suggestions are really appreciated, thx
LT (aka: Lindsey Thomson)

**Comment by hpresnall** [comment]
By defaults, the graphs display about 100 data points. The graph point that is shown is the _average_ for all the data recorded. In the app, this is called the `granularity`.  As you add data that extends the time period of the graph, the granularity updates to maintain the 100 data points.

You can change this in View->Set Granularity or CTRL-G. Disable automatic granularity and set your own value.

Note setting the granularity lower than the interval at which you collected data does not change anything. Also, the more data you have on the chart, the slower it will be. It will probably be noticeable once you have a few thousand data points.

It's should also be possible to create a custom report that displays the peak max (`GRANULARITY_MAX`) in a custom report. See http://nmonvisualizer.github.io/nmonvisualizer/customreports.html. This would be useful if you want to see a bar chart with a bar for each server and the max 60 second average CPU for the day or something similar.

**Comment by Lt0001us1** [comment]
very cool, many thx for all.


lt (lindsey thomson)
Aim high…work hard!
http://www.linkedin.com/in/lt0001us1

No Fear of Failure:
"I have learned the secret of being content in any and every situation,
whether well fed or hungry, whether living in plenty or in want. I can do
everything through him who gives me strength.”
* Philippians 4:12b-13 *
"Faith is not believing God can, it is knowing that God will."
Every Pro was once an Amateur; Every Expert was once a Beginner; So Dream
BIG and START NOW. "unknown"
