### ISSUE TITLE
need high peaks only avg in disk & cpu, how?

### ISSUE THREAD

**Issue by Lt0001us1** [nmonvisualizer/nmonvisualizer#46]
we are experiencing the graphs showing an avg instead of MAX points & we NEED MAX points to identify with our internal customers where the work load is real time MAX, not avg. yes, by reducing the time frame, the MAX is more displayed, however, we need MAX over 8 PLUS hours of data, any suggestions are really appreciated, thx
LT (aka: Lindsey Thomson)

**Comment by Lt0001us1** [comment]
we have read the PDF/blogs/etc, not really anything that explains how to ONLY avg the high peaks of disk & cpu

**Comment by hpresnall** [comment]
see #42
