### ISSUE TITLE
Need way to select colors or not do not use Yellow

### ISSUE THREAD

**Issue by petepdx** [nmonvisualizer/nmonvisualizer#47]
Is there a way to either select the color for entities or can the use of light colors such as yellow be changed ?

**Comment by hpresnall** [comment]
Not easily since this program is using the defaults from JFreeChart. It would be very tedious to provide a UI to set the colors of an arbitrary number of lines.

**Comment by scbray1** [comment]
Is there a properties file that could be modified ?
