### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by michaello1** [nmonvisualizer/nmonvisualizer#49]
Hello,

I try to load multiple nmon files but it get stuck after 23 nmon files (we have 1 nmon file every 12 hours). Observations:
  - I have never had this issue before. I was used to do analysis for 3 months (quarter analysis) this way - > 180 nmon files 
  - I tried `java -Xmx10240m`
  - It get stuck at the 23rd file where heap starts to grow and OOM follows
  - when I start analysis with 23rd file it works but it fails on 27th or so. I tried to skip 23rd file but it fails on 24th file
  - with nmon files from different quarter it fails the same way but it is able to process more nmon files
  - it happens on macOS with Java 9 and on Windows 2008 Server with Java 8

**Comment by hpresnall** [comment]
It may be that you just need more memory for a large number of files or files with a lot of data. But 10GB does seem like it should be enough unless you have more than 1GB of NMON files.

I have made one small change in the latest commit if you want to try that. It may only help when processing files with a lot of process / TOP data on IBM JVMs though. In my case, it saved about 200MB of memory when processing 3 files totaling 125MB. Heap used before the fix was about 800MB.

Past that, I will need to dig deeper which may take a while to get to with the holidays coming up.

**Comment by michaello1** [comment]
I can simulate high memory consumption (around 8,9 GB) with just 12 nmon files representing 6 days (3 MB per nmon file, 36 MB total). Those files are from AIX and I did complex analysis without problems in the past (I can process Q1/2017 and Q2/2017 without problems. Q3 and Q4 only when I find first bad day and divide interval to 2 parts). Probably some data causes this problem. Let me know if I can provide you more relevant information (like Eclipse MAT analysis or so).

I will try your latest patch a bit later.

**Comment by hpresnall** [comment]
I've made a few more changes but I don't think it's solving the main issue. Please try the latest commit though to see if anything is different.

Another thing you can try is to turn off logging. Go to Help -> View Log (CTRL-L). In the dialog that appears, change the log level drop down to `WARNING` or `OFF`.

I think it would help if I had your nmon files. Something is definitely wrong if 36MB of data is ballooning to 8.9 GB of heap.

Also, can you confirm that the Q1 and Q2 data are find now, with your current JVM and NMONVisualizer version? I want to make sure it's the data and not something about your current setup.

**Comment by michaello1** [comment]
Your changes did not help. And it can not compile with Java 9 (I locally fixed it with adding final keyword to the scroller variable):
`    [javac] /Users/user/Data/tools/NMONVisualiser/build/nmonvisualizer/src/com/ibm/nmon/gui/util/LogViewerDialog.java:95: error: local variable scroller is accessed from within inner class; needs to be declared final
    [javac]                 scroller.setViewportView(log);
    [javac]                 ^
    [javac] 1 error
    [javac] 4 warnings`

Today I was performing analysis of nmon files from IHS servers. I loaded 529 nmon files (1.12 GB in total, average 2.1 MB per file) and with 9.15 GB consumed memory I was able to work with NMONAnalyzer without problem. Then I tried to load nmon files from second IHS server and it stopped after 450th file (OOM). When I try it with smaller interval I can simulate memory pressure (again just 16 files, 33.9 MB in total). 

And yes Q1 and Q2 data are fine with Java 9 and compiled NMONVisualizer from source code.

Please write me an email (michael _at_ upcmail _dot_ sk) and I will send you a link to files.

**Comment by hpresnall** [comment]
Sent you an email last week requesting files.

**Comment by michaello1** [comment]
Thanks for the remainder. Check your email now.

**Comment by hpresnall** [comment]
I am pretty sure this due to logging and a possible issue with how JTextArea works. Can you turn off logging _before you process any data_ and then rerun with all your files? Go to Help -> View Log (CTRL-L). In the dialog that appears, change the log level drop down to OFF.

If you confirm that works, I will also add a patch that removes the logging that's happening with your files. Looking at that code again it's not needed anyway.

**Comment by michaello1** [comment]
It helped. I was able to load all 529 files from the second box. There is still some difference though. Parsing 529 files from the first box consumed around 9,3 GB memory. Parsing 529 files from the second box consumed around 10,8 GB memory. At the end it works so this is not a big issue.

Sorry that I missed your recommendation about logging before :/

**Comment by hpresnall** [comment]
Great!

I made another commit that should work without turning off logging. Can you confirm that has the same effect? If it works, I think we can close.

**Comment by michaello1** [comment]
Yes, it works perfectly. I have tested it with many inputs and always with success. Thank you!
