### ISSUE TITLE
not parsing big file 86mb of logs

### ISSUE THREAD

**Issue by Nurlan199206** [nmonvisualizer/nmonvisualizer#50]
Subject problem

**Comment by hpresnall** [comment]
Have you launched the app with a larger heap size? Something like `java -Xmx2048M -jar NMONVisualizer-xx.jar` should work.

If that does not work, try disabling logging as recommended in #49.

**Comment by Nurlan199206** [comment]
Thank you.

i ran application with another command, like that: java -XX:MaxHeapSize=1024m -jar NMONVisualizer_2017-08-08.jar

now working...
