### ISSUE TITLE
download link problem

### ISSUE THREAD

**Issue by seyedmab** [nmonvisualizer/nmonvisualizer#57]
i want to download 
https://bintray.com/nmonvisualizer/NMONVisualizer/download_file?file_path=NMONVisualizer_2018-04-10.jar
1- but link is not active and disabled. please repair problem
2- i want install nmonvisualizer on aix . is it possible ?

**Comment by hpresnall** [comment]
I've tried this on 2 different networks with 2 different devices and didn't have any problem. I also see a consistent number of downloads this week. Could it be a firewall or proxy on your end that is blocking jar file downloads?

It will run on AIX with any IBM JVM version greater than Java 6.

You can download and build from source if needed.
