### ISSUE TITLE
How to change colour of Nmon Visualizer charts by editing XML file or command line ?

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#58]
My charts are being produced in quite garish colours. Can I put something on the java command line or in the chart's XML file to change colours ? I would like to change text foreground/background colours and chart colours.

**Comment by hpresnall** [comment]
I think I have a rough idea of how to do this, along with #47 and #60. I'd need to add some code to the chart building logic and have a way to specify defaults in the app that get propagated to all the chart UI objects. This will take some work; I may be able to get to it over the holidays.

I am also thinking of a JSON file to support this. Something like:

    {
      "chartBackground": "white",
      "plotBackground": "grey",
      "text": "black",
      "chartElements": "black", // chart title, legend text, axes, axes text, tick marks
      "gridLines": "#bbbbbb",
      "chartItems": [ "blue", "red", "green", [ 120, 120, 120 ], "#aa0000" ]
    }

Note that colors can be color names (defined in [ChartColor](http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/ChartColor.html)  which includes `java.awt.Color`) , an RGB array or an HTML hex value.

The `chartItems` value can be an array to specify a set to colors to be cycled through for lines and bars.

If you didn't specify a value in the JSON it would revert to the default.

Does that seem like it would support what you need?

**Comment by scbray1** [comment]
Thanks. That would be a big improvement. Alternatively you could use a Java .properties file. That might be simpler.

I was also wondering if it would be possible to embed ANSI escape codes in the "name" fields. e.g. ANSI_RED = "\u001B[31m". I tinkered with that but it didn't work.

**Comment by hpresnall** [comment]
I've implemented this and ended up going with a properties file. Format supports color names, rgb values as arrays, and hex values (`#` and `0x`).

The default filename in the GUI is `chart.properties` and can be loaded via `View -> Chart -> Custom Format` or CTRL-SHIFT-F. From the command line, use `-f chart.properties`.

A sample "dark theme" would be:

    background=BLACK
    plotBackground=DARK_GRAY
    text=WHITE
    elements=[ 248, 248, 248 ]
    gridLines=0xa0a0a0
    annotations=GREEN
    series= VERY_LIGHT_RED, VERY_LIGHT_BLUE, VERY_LIGHT_GREEN, VERY_LIGHT_YELLOW, VERY_LIGHT_CYAN, VERY_LIGHT_MAGENTA, LIGHT_RED, LIGHT_BLUE, LIGHT_GREEN, LIGHT_YELLOW, LIGHT_CYAN, LIGHT_MAGENTA

Note the `series` element is a command separated list of colors to rotate through for lines and bars. You can mix the various ways of specifying a color in that list; they don't all have to be the same kind.

I've also removed yellow from the default list for #47.

Try this out and let me know. If everything is good, I can create a new release and update the website docs.
