### ISSUE TITLE
How to add Weighted Average to Nmon Visualizer Statistics ?

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#59]
How can I add Weighted Average (as described in the Nmon Analyser User Guide) to the Statistics of an Nmon Visualizer chart ? An example of its use is on the IOADAPT sheet of an Nmon Analyser output spreadsheet.

See also https://www.ibm.com/developerworks/community/blogs/aixpert/entry/nmon_for_aix_15_years_on_and_still_learning1?lang=en

**Comment by hpresnall** [comment]
This shouldn't be too hard to add. Just add the calculation to `AnalysisRecord` and add a new enum to `Statistic` and it would be possible to graph this with a custom chart.

The majority of the work in the GUI would be updating all the table models to support it. Not difficult, but tedious to update and test.

**Comment by hpresnall** [comment]
I've added this metric as a default on all the GUI charts. You can reference it in custom charts using `WEIGHTED_AVERAGE` as the statistic name.

Please pull the latest code and let me know if you find any issues.
