### ISSUE TITLE
How to put date in title of Nmon Visualizer chart

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#61]
Nmon Analyser appends hostname and date to the title of a chart, and doesn't use a subtitle, thus only consuming a single line on the chart. How can this be done in an Nmon Visualizer custom chart ?

**Comment by hpresnall** [comment]
Are you seeing the date now? If so, that would be because it's part of the hostname.

Right now you can set a `subtitledBy` attribute to chart XML elements that defines a pattern for the subtitle. This defaults to hostname. See the Naming & Legends section of http://nmonvisualizer.github.io/nmonvisualizer/customreports.html.

I could probably add a `DATE` option as a naming mode with a `HH:mm:ss MMM dd` format as the default. What do you think?

**Comment by scbray1** [comment]
I'm not seeing any date in the title or subtitle at the moment, but I would like to have the option of inserting one of the following: DD/MM/YYYY, HH:MM:SS  or DD/MM/YYYY HH:MM:SS. Better still, a format string that would allow for different international date formats. Or maybe something like %H for hostname, %T for type, %Y %m %d for dates, etc.

**Comment by hpresnall** [comment]
Sorry for the delay, but I finally found some time to work on this. You can now specify `subtitledBy="DATE"`  in charts. It will default to `HH:mm:ss MMM dd`.

If you want to customize that, you can use the `dateFormat` attribute in the chart element. This supports any format string supported by [SimpleDateFormat](https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html). In addition, you can also add the hostname, data type, field or statistic by using the keywords `HOST`, `TYPE`, `FIELD`, or `STAT`. So, something like `<linechart name="CPU Utilization" shortName="CPU" stacked="true" subtitledBy="DATE" dateFormat="HH:mm 'HOST' 'TYPE'">` would create a subtitle like `14:13 app1.foobar.com CPU_ALL`. Note that these keywords need to be single quoted.

**Comment by scbray1** [comment]
Thanks very much. Please can you put an updated jar file on the home page, so that I can try it out ?

**Comment by hpresnall** [comment]
Can you build from source? I'd like to fix another issue before creating a new version and this made enough changes that I'd like you to try it out before marking it 'official'.
