### ISSUE TITLE
Add method to chart only top processes

### ISSUE THREAD

**Issue by hpresnall** [nmonvisualizer/nmonvisualizer#62]
Per comment in #20 add a way to only chart the top processes rather than all of the processes.

**Comment by hpresnall** [comment]
I added a `$TOP_PROCESSES` pseudo-type that can be used in chart definitions instead of `$PROCESSES`. This is now in the default dataset chart list, replacing "CPU Utilization by Process"

**Comment by scbray1** [comment]
Will this also work for top 10 Memory by Process ?

**Comment by hpresnall** [comment]
It's only picking the top processes based on CPU. You could still use this with the `SIZE` data type but it would be size of the top CPU users, not necessarily the top memory users.

I could modify this to have one for CPU and one for memory.

**Comment by hpresnall** [comment]
Added another pseudo-type for memory. Now use `$TOP_PROCESSES_BY_CPU` or `$TOP_PROCESSES_BY_MEMORY`.
