### ISSUE TITLE
iostat graphs

### ISSUE THREAD

**Issue by rowswell** [nmonvisualizer/nmonvisualizer#67]
Using version 2019-01-06
Command: iostat -Tsf 1 30 (AIX 7.1 and AIX 7.2)
The IOStat Logical and Physical graphs both show Kbps as zero.
The IOStat Logical and Physical graphs both show Kb_read for the actual write column and Kb_wrtn graph is the read column (in the iostat data file).  The tps graph is showing the Kbps column in the data.

Thanks
Dean Rowswell

**Comment by hpresnall** [comment]
Sounds like something is off by one with the parser. Can you attach a sample file?

**Comment by rowswell** [comment]
[iostat.txt](https://github.com/nmonvisualizer/nmonvisualizer/files/2938775/iostat.txt)

**Comment by hpresnall** [comment]
Somehow this never worked right and I didn't notice it either. I've fixed some array handling errors. Please try building manually and ensure everything looks ok now.

**Comment by rowswell** [comment]
Hi Hunter - works great!  Thanks so much for the speedy fix and great tool by the way!   I use it mostly for nmon parsing but I can't find where/if nmon captures "iostat -f" data for filesystem I/O - so now I can simply run iostat -Tsf and then graph it with Visualizer.
