### ISSUE TITLE
shared storage pool graphs, where are they?

### ISSUE THREAD

**Issue by sk0al** [nmonvisualizer/nmonvisualizer#70]
I am using the latest VIOS on power8, vios version 3.1.0.21.  I added the -y flag sub=ssp, sub=sea but nmon visualizer_2019-04-06 does not display any data even though I can see it in the actual file.  I looked 2-3x for this data in the GUI, but cannot find it.

>grep -i ssp vios19a_190912_0000.nmon

>AAA,command,/usr/bin/topas_nmon -f -m /var/nmon **-y PCPU=on,SCPU=on,sub=sea,sub=ssp** -O -T -A -M -P -J -V -d -^ -s 60 -c 1440 -youtput_dir=/var/nmon/vios19a -ystart_time=00:00:01,Sep12,2019
BBBP,1958,mount,"         /var/vio/SSP/r2-clstr-1/D_E_F_A_U_L_T_061310 /var/vio/SSP/r2-clstr-1/D_E_F_A_U_L_T_061310 poolfs Aug 18 08:52                 "
BBBP,1984,df -m,"dvar/vio/SSP/r2-clstr-1/D_E_F_A_U_L_T_061310 88077696.00 54716647.28   38%        -      - /var/vio/SSP/r2-clstr-1/D_E_F_A_U_L_T_061310"
BBBSSP,000,Shared Storage Pool Information
BBBSSP,001,Cluster Name,Pool Name,Pool Size,Pool Used %
BBBSSP,002,r2-clstr-1,r2stgp-1,88077696,37.9
BBBSSP_CLIENT,000,SSP Client and LU Mapping stats
BBBSSP_CLIENT,001,PoolName_ClientId,Machine Type Model(MTM),LU Size Used
BBBSSP_CLIENT,002,r2stgp-1_13,8408-44E02783738X,927795
BBBSSP_CLIENT,003,r2stgp-1_32,9009-41A067807C30,529438
BBBSSP_CLIENT,004,r2stgp-1_16,8408-44E02783738X,242252
BBBSSP_CLIENT,005,r2stgp-1_8,8408-44E02783738X,2947250
BBBSSP_CLIENT,006,r2stgp-1_26,8408-44E02783738X,8551056
BBBSSP_CLIENT,007,r2stgp-1_27,8408-44E02783738X,5654052
BBBSSP_CLIENT,008,r2stgp-1_28,8408-44E02783738X,2176130
BBBSSP_CLIENT,009,r2stgp-1_23,8408-44E02783738X,989243
BBBSSP_CLIENT,010,r2stgp-1_35,8408-44E02783738X,252942
BBBSSP_CLIENT,011,r2stgp-1_18,8408-44E02783738X,292880
BBBSSP_CLIENT,012,r2stgp-1_25,8408-44E02783738X,998459
BBBSSP_CLIENT,013,r2stgp-1_19,8408-44E02783738X,2173058
BBBSSP_CLIENT,014,r2stgp-1_17,8408-44E02783738X,221707
BBBSSP_CLIENT,015,r2stgp-1_12,8408-44E02783738X,2250890
BBBSSP_CLIENT,016,r2stgp-1_24,8408-44E02783738X,624930
BBBSSP_CLIENT,017,r2stgp-1_36,8408-44E02783738X,261135
BBBSSP_CLIENT,018,r2stgp-1_38,8408-44E02783738X,261135
BBBSSP_CLIENT,019,r2stgp-1_21,8408-44E02783738X,190474
BBBSSP_CLIENT,020,r2stgp-1_20,8408-44E02783738X,512030
BBBSSP_CLIENT,021,r2stgp-1_15,8408-44E02783738X,571424
BBBSSP_CLIENT,022,r2stgp-1_29,8408-44E02783738X,250572
BBBSSP_CLIENT,023,r2stgp-1_34,9009-41A067807C30,202763
BBBSSP_CLIENT,024,r2stgp-1_9,8408-44E02783738X,338963
BBBSSP_CLIENT,025,r2stgp-1_22,8408-44E02783738X,190474
BBBSSP_CLIENT,026,r2stgp-1_31,8408-44E02783738X,529438
BBBSSP_CLIENT,027,r2stgp-1_33,8408-44E02783738X,330770
BBBSSP_CLIENT,028,r2stgp-1_30,8408-44E02783738X,440344`

Please advise and or add this enhancement!  Thank you

**Comment by hpresnall** [comment]
This information should be in the System Info dialog for each data set. In the tree view, right click on the hostname / dataset you want and select `System Info`. This should show a popup with a tab for each BBB data type.
