### ISSUE TITLE
-g parameter not taken into account in custom report command line

### ISSUE THREAD

**Issue by HMRaf** [nmonvisualizer/nmonvisualizer#71]
when typing the command line "NMONVisualizer_2018-04-10.jar com.ibm.nmon.ReportGenerator -g1 myfile.nmon", the CPU.png generate does not display the graph as 1 point each second.

Current behavior : -g1 plot graphics the same as if it was not passed in parameter

Expected behavior : -g1 plot graphics with granularity as 1point each second

**Comment by hpresnall** [comment]
Are you using the latest version (2019-04-06)? There was a bug fix for this issue in that release.
You should see the granularity value in stdout with this version: `Using granularity of 1s`.

**Comment by HMRaf** [comment]
Oh my bad, I was using older version. It is working fine with version 2019-04-06. Thank you for your assistance
