### ISSUE TITLE
Granularity is logged in seconds but it should be milliseconds

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#72]
-g 100000  sets the Granularity in milliseconds but Nmon Visualizer logs it as:
"Using granularity of 100000s".

**Comment by hpresnall** [comment]
-g is setting the granularity in seconds.
See http://nmonvisualizer.github.io/nmonvisualizer/commandline.html

It's stored internally in ms, but the command line parses and presents it after scaling
https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/ReportGenerator.java#L163
https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/ReportGenerator.java#L320

**Comment by scbray1** [comment]
But the log file says "100000s" when it should say "100000ms" or "100s".
