### ISSUE TITLE
subtitledBy="DATE" not working on Bar Chart

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#74]
I have added subtitledBy="DATE" to all my line charts without any problems, but when I added it to a bar chart HOST was not displayed and the displayed date string was incorrect:
I want to see:   12 Oct 2019
but it shows:    00:04:49 Oct 12

Here is an extract from my XML file:
  <barchart name="Disk Adaptors (KB/s)"
            shortName="IOADAPT_BAR"
            categoriesNamedBy="FIELD"
            barsNamedBy="STAT"
            stacked="True"
            subtractionNeeded="True"
            subtitledBy="DATE" dateFormat="'HOST' - dd MMM YYYY" >

    <yAxis label="KB/s"/>

    <data stat="AVERAGE">
      <type name="IOADAPT" />
        
        <field regex="(.*)-KB/s"  aliasByGroup="1"/>
    </data>

    <data stat="WEIGHTED_AVERAGE">
      <type name="IOADAPT" />
        <field regex="(.*)-KB/s" aliasByGroup="1"/>
    </data>

    <data stat="MAXIMUM">
      <type name="IOADAPT" />
        <field regex="(.*)-KB/s" aliasByGroup="1"/>
    </data>

  </barchart>

**Comment by hpresnall** [comment]
Does setting `dateFormat="'HOST' HH:mm:ss MMM dd"` in the `<barChart>` element give you what you want?

You might also need to set the `barsNamedBy` attribute to `STAT` or `FIELD_STAT` to get everything charted correctly.

If you want to play around with this, it might be easier to do it in the GUI. Select View -> Custom Report in the menu and it will load a window that you can load and reload the report xml as you make change.

**Comment by scbray1** [comment]
My message above was truncated for some reason. Here is the first part of the chart definition that I couldn't get to work for a bar chart:

  <barchart name="Disk Adaptors (KB/s)"
            shortName="IOADAPT_BAR"
            categoriesNamedBy="FIELD"
            barsNamedBy="STAT"
            stacked="True"
            subtractionNeeded="True"
            subtitledBy="DATE" dateFormat="'HOST' - dd MMM YYYY" >

    <yAxis label="KB/s"/>

**Comment by scbray1** [comment]
It was truncated again. I'll attach it instead.
[barchart.txt](https://github.com/nmonvisualizer/nmonvisualizer/files/3722593/barchart.txt)

**Comment by hpresnall** [comment]
That looks correct to me and it seems to be parsing ok. What isn't working?

**Comment by scbray1** [comment]
HOST was not displayed and the displayed date string was incorrect:
I want to see: HOST - 12 Oct 2019
but it shows: 00:04:49 Oct 12

**Comment by hpresnall** [comment]
Yes, this is a bug. Can you build from source and see if this fixes your issue?

In the current release you could also remove the `barsNamedBy` and `categoriesNamedBy` attributes to have the subtitle show up right, but I assume this won't be what you want.
