### ISSUE TITLE
NMON json file to rename hostnames

### ISSUE THREAD

**Issue by EstebanMonge** [nmonvisualizer/nmonvisualizer#75]
Hello I want to know if its possible to rename hostnames from CLI with a json file, and how I can do it.

**Comment by hpresnall** [comment]
Build the latest version and you can use `-h <hostrenamer.json>` on the command line. The JSON file has the format as documented in http://nmonvisualizer.github.io/nmonvisualizer/renaming.html.

**Comment by EstebanMonge** [comment]
It works!:

	/home/emonge/nmon/idcgbmadmipa01_191123_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191124_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191125_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191126_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191127_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191128_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191129_0000.nmon... Complete
	/home/emonge/nmon/idcgbmadmipa01_191130_0000.nmon... Complete
Parsing complete!

Using granularity of 25890s

Charting interval All Data: 00:00:02 Nov 01 - 23:19:03 Nov 30
Writing charts to /home/emonge/nmon/charts
	Creating summary charts .......... Complete (10/10)
	Creating charts for renamed .................. Complete (18/18)
Charts complete!
emonge@angello:~/nmon$
