### ISSUE TITLE
I am unable to load nmon files beyond 41

### ISSUE THREAD

**Issue by krnchrn** [nmonvisualizer/nmonvisualizer#79]
Hi Team,

I am unable to load nmon files beyond 41. i need to analyze long duration.
Please help.
![Nmon_error](https://user-images.githubusercontent.com/54265584/84578507-c1f69700-ad7a-11ea-9e62-fddbe86207f7.jpg)

**Comment by hpresnall** [comment]
You probably don't have the JVM heap set large enough. Try `java -Xmx8192M -jar NMONVisualizer-<version>.jar`.
