### ISSUE TITLE
I am unable to load Perfmon file

### ISSUE THREAD

**Issue by jagssonawane** [nmonvisualizer/nmonvisualizer#80]
While loading specific performance counter file, I am getting error "cannot redefine DataType ". This is happening to specific performance counter file, others are working correctly. I tried to debug the code and found the failure is happening at parsing performance counter "Process". It tries to add uniqueId in format "Process -NUM@TIMESTAMP" for e.g. Process -10@15402123122

**Comment by hpresnall** [comment]
This may be due to process ids being reused. Can you find and rename the failing column in the perfmon file? 

If that doesn't work, I can take a look if you send me the file.

**Comment by jagssonawane** [comment]
I thought of same doubt, I gave try multiple time but no success, here I am sharing link counter file as it is 70 mb of size. If I get a fix that will be helpful.
https://drive.google.com/drive/folders/159OZNWnNb4q4R7AzWMYCAgeUpHScYNhn?usp=sharing

**Comment by hpresnall** [comment]
It seems like perfmon has changed formats. I will need to make some updates for this to work. Unfortunately, I am having computer issues and it may be a few days until I can try and fix.

**Comment by hpresnall** [comment]
I've made some updates to the perfmon processor. It was not splitting the lines correctly nor was it handling Windows complex process naming scheme.

These fixes allow processing of the file you uploaded. Can you please build from the master branch and confirm this works on all your files?

Did you expect there to be 35,000 columns in this file?! That turns into 2,586 DataTypes. I don't know if I've seen that many before. 👍

**Comment by jagssonawane** [comment]
Thanks, buddy. Files are loading correctly without any issues. About files, due to all instances inclusion in performance category counters, that contributed to these many columns.
