### ISSUE TITLE
AIX nmon TOP CPU% incorrect

### ISSUE THREAD

**Issue by kgibm** [nmonvisualizer/nmonvisualizer#82]
I can't upload the full nmon file but here are the relevant snippets:

```
AAA,AIX,7.1.5.16

CPU_ALL,CPU Total digimfpproddb02,User%,Sys%,Wait%,Idle%,Busy,PhysicalCPUs 
LPAR,Logical Partition digimfpproddb02,PhysicalCPU,virtualCPUs,logicalCPUs,poolCPUs,entitled,weight,PoolIdle,usedAllCPU%,usedPoolCPU%,SharedCPU,Capped,EC_User%,EC_Sys%,EC_Wait%,EC_Idle%,VP_User%,VP_Sys%,VP_Wait%,VP_Idle%,Folded,Pool_id
TOP,+PID,Time,%CPU,%Usr,%Sys,Threads,Size,ResText,ResData,CharIO,%RAM,Paging,Command,WLMclass

CPU_ALL,T1109,19.8,24.9,0.5,54.8,44.8,48
LPAR,T1109,5.969,12,48,20,8.00,200,0.00,29.84,29.84,1,0,19.82,24.94,0.25,29.58,13.22,16.63,0.17,19.72,0,0
TOP,63767174,T1109,294.69,130.94,163.74,509,1432352,200,1432188,16087708,2,105,db2sysc,Unclassified
```

This is reporting that PID 63767174 CPU% is 294.69%. There are 12 physical CPUs, so the effective CPU% of this PID is 24.5%; however, by default, with the `Scale Process Data by CPUs` option checked, CPU% is instead scaled to 6.13. This is because [NMONParser.scaleProcessDataByCPUs](https://github.com/nmonvisualizer/nmonvisualizer/blob/b453130c3fb564418e0658c143afb32a7900140e/src/com/ibm/nmon/parser/NMONParser.java#L830) cannot find PCPU_ALL:

```
$ grep -c PCPU_ALL digimfpproddb02_200817_0001.nmon 
0
```

So then this code doesn't find the number of CPUs:

```
        // use the cpu count from the file if no data is available at a given time
        double CPUs = fileCPUs;

        if (isAIX) {
            DataType cpuAll = data.getType("PCPU_ALL");

            // hasData should also cover cpuAll == null
            if (currentRecord.hasData(cpuAll)) {
                CPUs = currentRecord.getData(cpuAll, "Entitled Capacity");
            }
        }
```

Thus it falls back to `fileCPUs` which is the number of logical CPUs. In this example, that's 48, thus `294.69 / 48 = 6.13`.

So the basic issue is that there is no PCPU_ALL data. I presume the fix is to use the LPAR line's PhysicalCPU, but then I start to wonder, why is this using PCPU_ALL's Entitled Capacity? Is that even valid? First, isn't PCPU_ALL the amount of measured CPU usage, whereas don't we want to set `CPUs` to the maximum number of CPUs? Second, wouldn't we want to compare to total CPUs rather than entitled?

In addition, I didn't understand why [NMONParser.parseTopData](https://github.com/nmonvisualizer/nmonvisualizer/blob/b453130c3fb564418e0658c143afb32a7900140e/src/com/ibm/nmon/parser/NMONParser.java#L613) is calculating %Wait as `%CPU - %Usr - %Sys`. This calculation is invalid since the CPU isn't scaled so the value ends up being less than 0.

```
                if (i == 3) {
                    recordData[i] = recordData[0] - recordData[1] - recordData[2];

                    // Wait% is less than 0 assume rounding errors in CPU%
                    // fix errors and set Wait% to 0;
                    if (recordData[i] < 0) {
                        recordData[0] -= recordData[i];
                        recordData[i] = 0;
                    }
                }
```

For anyone finding this issue, the workaround is to deselect `Scale Process Data by CPUs` **before** processing the nmon file and then you just see the raw values and you can mentally scale by PhysicalCPUs.

**Comment by kgibm** [comment]
Created PR https://github.com/nmonvisualizer/nmonvisualizer/pull/83

**Comment by hpresnall** [comment]
Good find. This code is very old and was written before either a) I understood LPAR CPU allocation or b) it got this complex, so I am not surprised things like this aren't right.

I think I used entitled CPU because I wanted scaled values larger than 100% to indicate the LPAR was using _more_ than it's entitlement.

%CPU, %sys and %usr are all being scaled with this code:
```
if (CPUs > 1) {
            for (String field : processType.getFields()) {
                if (field.startsWith("%")) {
                    // assume %CPU, %Usr, %Sys or %Wait
                    values[processType.getFieldIndex(field)] /= CPUs;
                }
            }
        }
```
So, I think the calculation for %wait is ok if the scale factor is correct.

Before I accept the PR, do you want to change anything else?

**Comment by kgibm** [comment]
@hpresnall Makes sense. I've updated the PR to use entitled instead of physicalCPUs.

**Comment by kgibm** [comment]
Thanks!
