### ISSUE TITLE
How to specify more than one xml file

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#84]
The web page https://nmonvisualizer.github.io/nmonvisualizer/commandline.html says:
"The -d, -a, --mt and --mf switches ... can be specified multiple times to create a number of custom reports at once."

It would be very useful to add a complex example to that web page. For example:

What options do I need to specify to produce all the reports that you get by default when you specify no options. i.e.:
java -jar %NMON_VIZUALIZER_JAR% com.ibm.nmon.ReportGenerator %NMON_FILE%

Is this right ?
java -jar %NMON_VIZUALIZER_JAR% com.ibm.nmon.ReportGenerator --nodata --nosummary -d %NMON_TOOLS%\summary_all_intervals.xml -d %NMON_TOOLS%\summary_single_interval.xml %NMON_FILE%

The output from the command doesn't make it clear which xml files and chart definitions are being used when processing the nmon file. Please can you add some extra information to the output so that we can monitor what is happening ?

**Comment by hpresnall** [comment]
How does that update look?

**Comment by scbray1** [comment]
I looked on https://nmonvisualizer.github.io/nmonvisualizer/commandline.html but I can't see your changes.

I see only this line which produces the default charts:
java -jar NMONVisualizer_<release_date>.jar com.ibm.nmon.ReportGenerator <file|directory to parse>

I would like to see a line like this which, if correct, would produce exactly the same default charts:
java -jar NMONVisualizer_<release_date>.jar com.ibm.nmon.ReportGenerator --nodata --nosummary -d summary_all_intervals.xml -d summary_single_interval.xml <file|directory to parse>

**Comment by hpresnall** [comment]
Sorry changes aren't live yet, only in the commit https://github.com/nmonvisualizer/nmonvisualizer/commit/a823ed12b7668a56255067a44c44ee5855626810

I don't have the line exactly, but you could reconstruct it with that info.
However, not sure why you need to. If you specify  -d, -a, --mt or --mf but not -nodata and --nosummary, custom _and_ default charts should all be created.

**Comment by scbray1** [comment]
I would like to specify all the default charts but then modify some of them by editing the xml files. That's why I need to know which xml files to specify with multiple -d options.

**Comment by hpresnall** [comment]
Added a line. Can you confirm this is correct?
`--nodata --nosummary -d <nmon_code>/src/com/ibm/nmon/report/dataset_report.xml -a <nmon_code>/src/com/ibm/nmon/report/summary_single_interval.xml <file|directory to parse>`

**Comment by scbray1** [comment]
Yes, that looks OK, I think. So summary_all_intervals.xml is not in the default charts >

**Comment by hpresnall** [comment]
summary_all_intervals.xml is what is used in the GUI when you check Graph All Intervals. Note that is has only `<intervalchart>` elements.

Also, for reference you can use -a or -d for any xml file, but depending on the chart definition, the output could be wrong or not make sense.

For example, CPU utilization in dataset_report.xml:

```
  <linechart name="CPU Utilization" shortName="CPU" stacked="true">
     <yAxis label="% CPU" asPercent="true" />
     <data>
       <host os="UNIX" />
       <type name="CPU_ALL" />
       <field name="User%" alias="User" />
       <field name="Sys%" alias="System" />
       <field name="Wait%" alias="Wait" />
     </data>
...
```
There are multiple fields so there will be three lines, named by the field name (the default). If you passed this with `-a` then the same lines would be overwritten for each host. The resulting chart would have data for only the last host and there would be no indication of this.

Compare with summary_single_interval.xml:
```
  <linechart name="CPU Utilization" shortName="CPU over Time" linesNamedBy="HOST" subtitledBy="NONE">
    <yAxis label="% CPU" asPercent="true" />
    <data>
      <host os="UNIX" />
      <type name="CPU_ALL" />
      <field name="CPU%" alias="% CPU"/>
    </data>
...
```

Note there is only one field and `linesNamedBy="HOST"` is set. This means that with `-a`, each %CPU field will be named for the host and will not be overwritten. You _could_ specify this file with `-d` but then the graph wouldn't be as useful - there would only be a single line with the one hostname in the legend.
If you wanted User, System and Wait for each host, you could specify those fields, _and_ `linesNamedBy="HOST_FIELD"` but that could create a lot of lines on one chart which may be hard to read.

**Comment by scbray1** [comment]
Got it. Thanks very much.
