### ISSUE TITLE
nmon visualizer unable to parse the below files

### ISSUE THREAD

**Issue by fredriklundholm** [nmonvisualizer/nmonvisualizer#89]
[dx1091-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800802/dx1091-dat.zip)
[dx1093-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800803/dx1093-dat.zip)
[dx1105-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800804/dx1105-dat.zip)
[dx1106-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800805/dx1106-dat.zip)
[dx1107-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800806/dx1107-dat.zip)
[dx1108-dat.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/6800808/dx1108-dat.zip)

**Comment by hpresnall** [comment]
These nmon files looks like they got corrupted somehow.

For instance, dx1091 has a blank at line 78,111 then repeats data starting at CPU014 for timestamp T0366:

    DISKBSIZE,T0366,15.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0
    
    CPU014,T0366,60.4,2.3,0.0,37.3,0.0

dx1105 has a missing first column at line 59,812.

I didn't look at the other files, but you should be able to delete the duplicate / incorrect data from the file and reprocess it.
