### ISSUE TITLE
JFSFILE report via CLI

### ISSUE THREAD

**Issue by EstebanMonge** [nmonvisualizer/nmonvisualizer#9]
Hello I want to generate the JFSFILE report vía command line... but I dont know how do it.

I downloaded the file:
https://github.com/nmonvisualizer/nmonvisualizer/blob/master/src/com/ibm/nmon/report/dataset_report.xml

That contains the report but when I executed:
 java -jar NMONVisualizer.jar com.ibm.nmon.ReportGenerator -a stuff/dataset_report.xml /opt/nmon/14/11/

or 
 java -jar NMONVisualizer.jar com.ibm.nmon.ReportGenerator -d stuff/dataset_report.xml /opt/nmon/14/11/

Never output the png with JFSFILE graphs... What I am doing wrong?

Thanks a lot for your great work

**Comment by hpresnall** [comment]
The only chart that uses JFSFILE data is the `Percent Disk Space Used by File System` bar chart. This would be saved as `Disk Space.png`.

Do you see other PNG files but not this one? If there is no data for the chart, it will not be output. You can verify this by loading the nmon files in the GUI and looking at the JFSFILE data.

Also, note that you don't need to explicitly download and reference the `dataset_report.xml` file. These charts are automatically generated by default (use `--nodata` to prevent this).

**Comment by EstebanMonge** [comment]
Hello. Thanks for your answer. I checked the graph and is saved as Disk Space.png, but I want the same information like the line chart that you can see in the GUI vía: Hostname->JFSFILE

The reason is that if the mount point is large in the bar chart graph the names are cut.

**Comment by hpresnall** [comment]
If you just want to shorten the names of the mount points, you can do that with a `<field>` element. Copy the bar chart definition from `dataset_report.xml` and add something like this after _each_ `<type>` element:

    <field name="/dev/mapper/mpathbp1" alias="database" />
    <field regex="(.*)" />

The first element renames a specific disk to 'database' on the chart. The regex field displays all the other disks as-is.

If you want to do a line chart, something like this should work:

    <linechart name="Percent Disk Space Used by File System" shortName="Disk Space">
      <yAxis label="% Used" asPercent="true" />
      <data>
        <host os="UNIX" />
        <type name="JFSFILE" />
        <field name="/dev/mapper/mpathbp1" alias="database" />
        <field regex="(.*)" />
      </data>
    </linechart>

Put this in a separate xml file and reference it with `-d` on the command line. This will overwrite the default `Disk Space.png` file.

See the [documentation](http://nmonvisualizer.github.io/nmonvisualizer/customreports.html) for more info.
