### ISSUE TITLE
Undefined data type CPUUTIL000

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#90]
I am running nmon on Red Hat Enterprise Linux with this command:
nmon -F $LOG_FILE_NAME -m $DAILY_LOG_DIR -t -U -r "nmon_25h" -s120 -c750

-U = CPU utilisation stats - all 10 Linux stats:
     user, user_nice, system, idle, iowait, irq, softirq, steal, guest, guest_nice

The nmon log file contains:
CPUUTIL_ALL,CPU Util Stats nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL001,CPU Util Stats CPU1 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL002,CPU Util Stats CPU2 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL003,CPU Util Stats CPU3 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL004,CPU Util Stats CPU4 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL005,CPU Util Stats CPU5 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL006,CPU Util Stats CPU6 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL007,CPU Util Stats CPU7 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL008,CPU Util Stats CPU8 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL009,CPU Util Stats CPU9 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL010,CPU Util Stats CPU10 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL011,CPU Util Stats CPU11 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL012,CPU Util Stats CPU12 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL013,CPU Util Stats CPU13 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL014,CPU Util Stats CPU14 nmon_25h,User%,Nice%,Sys%,Idle%,Wait%,Irq%,Softirq%,Steal%,Guest%,Guest_nice%
CPUUTIL_ALL,T0001,74.01,7.19,114.24,1126.61,0.00,0.00,1.44,0.00,0.00,0.00
CPUUTIL000,T0001,2.16,0.72,5.75,86.22,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL001,T0001,2.16,0.72,9.34,81.91,0.00,0.00,0.72,0.00,0.00,0.00
CPUUTIL002,T0001,3.59,0.72,10.06,79.04,0.00,0.00,0.72,0.00,0.00,0.00
CPUUTIL003,T0001,2.87,0.72,6.47,84.06,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL004,T0001,2.87,0.72,10.78,80.47,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL005,T0001,2.16,0.72,8.62,82.63,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL006,T0001,3.59,0.72,10.06,81.19,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL007,T0001,8.62,0.00,7.90,77.60,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL008,T0001,8.62,0.72,8.62,78.32,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL009,T0001,7.19,0.00,7.19,80.47,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL010,T0001,7.90,0.72,7.90,78.32,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL011,T0001,8.62,0.00,8.62,76.88,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL012,T0001,7.19,0.72,8.62,77.60,0.00,0.00,0.00,0.00,0.00,0.00
CPUUTIL013,T0001,9.34,0.00,4.31,81.19,0.00,0.00,0.00,0.00,0.00,0.00
etc.

On processing the nmon log with NMONVisualizer_2021-04-04.jar using the command
java -jar ${NMON_VIZUALIZER_JAR} com.ibm.nmon.ReportGenerator --nodata --nosummary -d ${XML_FILE} -g 100 ${NMON_FILES}/${NMON_FILE} >> ${NMON_VISUALIZER_LOG} 2>&1

I see warning messages like this:
WARNING  undefined data type CPUUTIL000 at line 1063
WARNING  undefined data type CPUUTIL000 at line 1106
WARNING  undefined data type CPUUTIL000 at line 1260
etc.

These warnings point to the first line of each block beginning
CPUUTIL000,T0001,2.16,0.72,5.75,86.22,0.00,0.00,0.00,0.00,0.00,0.00

**Comment by hpresnall** [comment]
This seems like an NMON bug. It’s not outputting a CPUUTIL000 header line so the parser doesn’t know there will be any data for it later.

Those warnings are annoying but the rest of the file should have parsed fine. If you want to get rid of them, you can add a CPUUTIL000 header. I am not sure if this works if you make it the first line of the file or if you have to add it with the others. The other, maybe easier option is to remove all the CPUUTIL000 lines from the file with something like grep -v.

**Comment by scbray1** [comment]
Thanks very much for the fast response. Do you know where I can report this nmon bug ?

**Comment by hpresnall** [comment]
Maybe try https://sourceforge.net/p/nmon/bugs/

**Comment by scbray1** [comment]
I raised an nmon bug. See:
https://sourceforge.net/p/nmon/bugs/26/
