### ISSUE TITLE
Link to overview presentation PDF file doesn't work

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#91]
https://nmonvisualizer.github.io/nmonvisualizer/index.html 
has a link to an overview presentation PDF file - but it doesn't work.

**Comment by hpresnall** [comment]
Oops. This got deleted when bintray was discontinued. I should be able to get it back up tonight on GitHub.

**Comment by hpresnall** [comment]
Back up and hosted on github. The info in there is pretty old but I don't think the GUI has changed too much.
