### ISSUE TITLE
How to change Max value on y-axis in GUI ?

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#93]
I would like to modify the y-axis of a chart shown in the NmonVisualizer GUI to scale it to the same size as another chart. How can I do it ?

**Comment by hpresnall** [comment]
Right click on the chart and select `Properties ...`
Plot tab -> Range Axis
Range Tab - > uncheck `Auto-adjust range`
Set whatever values you want.

Without looking in more detail at the code, I am not sure when the graph will be reset / recreated so these may change back.
Regardless, you can right click on the chart again and click Save Chart to save a PNG of it with your modified axis.

**Comment by scbray1** [comment]
Thanks. It would be nice to add a page to https://nmonvisualizer.github.io/nmonvisualizer/NMONVisualizerOverview.pdf to provide a list of all the ALT- and CTRL-ALT keys.
