### ISSUE TITLE
SYS_SUMM for Nmon Visualizer

### ISSUE THREAD

**Issue by scbray1** [nmonvisualizer/nmonvisualizer#95]
Does Nmon Visualizer provide anything like Nmon Analyser's SYS_SUMM ? 
From https://nmon.sourceforge.net/pmwiki.php?n=Site.Nmon-Analyser doc inside zip file:

SYS_SUMM
This section is entirely generated by the Analyser and contains a useful summary of data taken
from other sheets. Note the the avg/max values for User%, Sys%, Wait% and Idle% are
independent and will not add up to 100%. The CPU% column shows avg/max values for the
sum of usr%+sys% during each interval. For micro-partitions, the values are shown as a
percentage of the Virtual Processors – they do not relate to the CPU_ALL values.
For non-partitioned or dedicated CPU partitions the graph shows the total CPU Utilisation (%usr
+ %sys) together with the Disk I/O rate (taken from the DISKXFER sheet) by time of day. For
micro-partitions the graph shows the number of physical CPUs being used instead of CPU%.
The value “Max:Avg” is simply the maximum value divided by the average. If monitored over a
long period of time the value for CPU% can be useful in spotting a system reaching saturation
level (the ratio will steadily decrease). If you have historical data then the value can also be
useful in determining how much latent demand is present in a system running at saturation level.

**Comment by hpresnall** [comment]
Possibly you can get similar data from the Table view (View -> Summary Table). You can drag and drop metrics from the left hand side into this table then display the min/max/avg (right click on the table -> Select Columns to pick which ones) for each metric over the interval. If there are multiple systems, the table will include data for each system.

You can also right click on the table and Copy All to put the data into the clipboard as CSV.

Note that stats are calculated over the given interval (defaults to all data). So, you could set different intervals and copy out the CSV data into a spreadsheet if needed. You can also get some of the similar data by clicking Graph All Intervals at the top right of the chart window, right clicking on the chart and selecting Copy Chart Data to put all the data points (avgs for each interval) into the clipboard.

**Comment by scbray1** [comment]
Thanks. I've just noticed that the CPU_ALL chart has a table below it that cotains exactly the data I need. How can I alter my command line xml file to export that table to a file ?

**Comment by hpresnall** [comment]
From the command line, there isn't a way to generate the chart summary data - that's a GUI only feature. You could output a CSV file from the command line using the `--rawdata` option. This will create one large CSV file for each NMON host which you could then analyze with Python/Pandas or open in a spreadsheet.
