### ISSUE TITLE
faulty line graphs since NMONVisualizer 2019-04-06.jar (or newer) when creating custom reports. 

### ISSUE THREAD

**Issue by Bromarv** [nmonvisualizer/nmonvisualizer#97]
Hi, 
based on NMONVisualizer_2019-04-06.jar (same for 2020-02-29 and 2021-04-04 (latest)) faulty line graphs occurred - see attached 1st RunQueue_bad_lines.PNG.

When using older version, e.g. NMONVisualizer_2016-02-29.jar based on IBM J9 version 8.0.7.20 (or Semeru 8) line graphs are displayed correctly - see attached 2nd RunQueue_good_lines.PNG.

Tried to update NMONVisualizer_2016-02-29.jar, because of updating Java 8 to Java 17 (issue occurred with J9 and hotspot jvms for all version 8, 11 and 17.).

Using NMONVisualizer_2016-02-29.jar, based on Java 11 or 17 led to " java.lang.reflect.InvocationTargetException":

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.ibm.nmon.DelegatingMain.main(DelegatingMain.java:37)
        ... 5 more
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.ibm.nmon.NMONVisualizerApp.<init>(NMONVisualizerApp.java:40)
        at com.ibm.nmon.ReportGenerator.<init>(ReportGenerator.java:333)
        at com.ibm.nmon.ReportGenerator.main(ReportGenerator.java:236)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 13 more

NMONVisualizer-2019-04-06.jar and newer worked with Java 11 and 17, but with faulty line graphs. 
Thanks for your help and best regards
Oliver

![RunQueue_bad_lines](https://user-images.githubusercontent.com/26147005/220929998-15df95d0-6190-460d-932e-80dfed9a39a1.PNG)
![RunQueue_good_lines](https://user-images.githubusercontent.com/26147005/220930003-ffe181c5-960d-4693-a150-3af47766dcc0.PNG)

**Comment by hpresnall** [comment]
This is strange. I am going to have to dig into this. I have been using the tool recently with openjdk 11 and haven't seen this behavior. Is this for all charts or just certain ones?

Can you share your NMON file?

There is some gap detection calculations in the code. Not sure how math would have changed in JVM versions, but anything is possible. Can you try deleting the custom version of the JFreeChart code at `src/org/jfree/chart/renderer/xy/StandardXYItemRenderer.java` and building the jar file?

**Comment by hpresnall** [comment]
Can't reproduce with the nmon files I have on MacOS with open JDK 17.0.6 or 19.0.2 from homebrew

**Comment by Bromarv** [comment]
Hi, in the meantime I have updated to NMONVisualizer_2021-04-04.jar and used it with IBM Semeru 17.0.9 and 21.0.1. When loading nmon data of two different hosts, then the summary view chart will contains interrupted line-graphs.

**Comment by Bromarv** [comment]
![Run_Queue](https://github.com/nmonvisualizer/nmonvisualizer/assets/26147005/c2a5c7ba-6cfb-4ba0-b476-395d8a4dae47)

**Comment by hpresnall** [comment]
I apologize that this completely dropped off my radar and I haven't looked into it.

I'm pretty sure this is happening because the difference in data collection time on the 2 hosts is just enough off that it's triggering the "don't draw a line" logic. But, I don't know why it worked on an other version unless something in the underlying JFreeChart changed.

Does changing the granularity (CRTL-G or View -> Set Granularity) to a value smaller than the NMON interval fix the issue?

**Comment by Bromarv** [comment]
I have tried different granularities. Unfortunately without success. I have uploaded an archive which contains two nmon files. If I display the nmon files individually, the line graphs are displayed correctly. Charts with min. 2 or more nmon files leads to incorrect line-graphs. 

And thank you very much for taking the time to support me.
[2nmon_files.zip](https://github.com/nmonvisualizer/nmonvisualizer/files/14075519/2nmon_files.zip)

**Comment by hpresnall** [comment]
Running on Mac with Java 21, I could not recreate this using ReportGenerator with args `--chartdata --nosummary --nodata -a test.xml ./nmon`, where test.xml is

```
<?xml version="1.0" encoding="UTF-8"?>
<charts>
  <linechart name="Run Queue" shortName="Run Queue" linesNamedBy="HOST">
    <yAxis label="Queue Length" />
    <data>
      <type name="PROC" />
      <field name="Runnable" alias="Run Queue" />
    </data>
  </linechart>
</charts>
```

However, there were some bugs in the calculation of the "gap threshold" used to determine when to draw connecting lines. Could you build the `gapfix` branch and see if that resolves your issue?

**Comment by Bromarv** [comment]
Hi, compiled the NMONVisualizer_2024-01-29.jar based on branch gapfix with Java 17. I have  used Java 17 and 21 for chart generation. Now, the chart contains consistent dotted lines and no mix of line and dotted graphs. We would like to have lines graphs again :-) Tried different granularities, but it looks like, that the granularity has no impact.

**Comment by hpresnall** [comment]
So, it's all dots now with no lines anywhere? That is very weird.

How are you generating the graphs - can you post any custom report files?

One thing to try would be to comment out [these lines](https://github.com/nmonvisualizer/nmonvisualizer/blob/f2edef3363339610c53ac85d8724901b605bbbf2/src/com/ibm/nmon/gui/chart/builder/LineChartBuilder.java#L130-L133), rebuild and see if that fixes the issue.

**Comment by Bromarv** [comment]
Hi, I have commented out the line 130, 131 and 133, compiled new NMONVisualizer_2024-02-06.jar based on Java 17 and branch gapfix. We have dotted lines, if data from more than one host is available at the same time, there are line charts if only data from one host needs to be displayed.

**Comment by hpresnall** [comment]
I am not sure what the issue is unless it is something with J9 / IBM jvms.
Have you tried with openjdk?

**Comment by Bromarv** [comment]
Hi, I have tried Open JDK 17 and 21 (temurin), too. Same behavior.

**Comment by Bromarv** [comment]
Hi, after moving from Ant to Maven the line graphs are looking as expected.

#99  https://github.com/nmonvisualizer/nmonvisualizer/pull/99

will fix #97. 

Thanks for your help.

**Comment by hpresnall** [comment]
I've merged @kgibm changes and updated the versions for some libraries. Can you confirm again that everything is working with a build from the master branch?

**Comment by Bromarv** [comment]
Hi, with a build from the new master branch based on maven, the dotted lines came back where I was expecting line graphs.

**Comment by hpresnall** [comment]
I'm wondering if it's related to the changes made in StandardXYItemRenderer. Can you 
1) remove the `<filter>` for that file in the pom https://github.com/nmonvisualizer/nmonvisualizer/blob/master/pom.xml#L114 
2) delete src/org/jfree/chart/renderer/xy/StandardXYItemRenderer.java

and see if that fixes it

**Comment by kgibm** [comment]
That's interesting because I provided a build from the same branch to @Bromarv and it worked for him. Maybe there's something non-deterministic happening in how the JAR is compiled or packaged which drives different classloading.

**Comment by kgibm** [comment]
Oh, interesting, I can reproduce the issue if I pull the latest `master` branch, but if I switch to my `issue97` branch, the problem goes away, so it seems to be related to the extra two commits since branch issue97...

**Comment by hpresnall** [comment]
I added a5ecb86 in order to fix your issue. The previous code wasn't actually working like I wanted.
If I could get that code working and remove the custom StandardXYItemRenderer, that would be ideal.

@kgibm how are you reproducing this?

**Comment by kgibm** [comment]
Interesting, ok. I'm just switching between commits and rebuilding:

Reproduce issue:

```
git checkout master
mvn clean install
java -jar NMONVisualizer_2024-02-13.jar
```

Then load the two NMONs provided and click on CPU over Time under All Systems.

To resolve the issue:

```
git checkout ef5215e453bd9f95fc59cc5bfff9bb2a3555cae5
mvn clean install
java -jar NMONVisualizer_2024-02-13.jar
```

Here's my Java on macOS ARM64:

```
$ java -version
openjdk version "17.0.9" 2023-10-17
IBM Semeru Runtime Open Edition 17.0.9.0 (build 17.0.9+9)
Eclipse OpenJ9 VM 17.0.9.0 (build openj9-0.41.0, JRE 17 Mac OS X aarch64-64-Bit 20231017_458 (JIT enabled, AOT enabled)
OpenJ9   - 461bf3c70
OMR      - 5eee6ad9d
JCL      - 3699725139c based on jdk-17.0.9+9)
```

From IBM Semeru Runtimes: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

**Comment by Bromarv** [comment]
Hi, with "git checkout ef5215e453bd9f95fc59cc5bfff9bb2a3555cae5" I get line-charts as expected. 

Base on master branch:
Removed the <filter> for that file in the pom https://github.com/nmonvisualizer/nmonvisualizer/blob/master/pom.xml#L114 and deleted src/org/jfree/chart/renderer/xy/StandardXYItemRenderer.java and got dotted lines.

**Comment by hpresnall** [comment]
Please try the latest. It seems to be working for me but confirmation would be good.

The original code wasn't right at all; neither was my first update. I hope I have it right now. Still not sure how it ever worked or why it broke.

**Comment by Bromarv** [comment]
Confirmed. Line graphs look like line graphs again. Thank you very much for your support.

**Comment by kgibm** [comment]
Also confirmed, thanks
